// communication.h - Implementation of nccl functions allreduce/allgather/reducescatter
#pragma once

#if USE_NVSHMEM

// nccl.h - NCCL Runtime for Program Generated by Mirage
#include <nccl.h>
#include <mpi.h>

#define NCCLCHECK(cmd) do {                         \
  ncclResult_t r = cmd;                             \
  if (r!= ncclSuccess) {                            \
    printf("Failed, NCCL error %s:%d '%s'\n",       \
        __FILE__,__LINE__,ncclGetErrorString(r));   \
    exit(EXIT_FAILURE);                             \
  }                                                 \
} while(0)

#endif
