name: "Report Bug"
description: "Report a bug in the project"
title: "[Bug] - Brief Description"
labels: ["bug"]
assignees: []

body:
  - type: textarea
    id: bug_description
    attributes:
      label: "Bug Description"
      description: "Provide a detailed description of the bug."
      placeholder: "Enter bug description here..."
    validations:
      required: true

  - type: textarea
    id: build_env
    attributes:
      label: "Build Environment"
      description: "Provide details about your build environment (e.g., OS, dependencies, versions)."
      placeholder: "Enter build environment details here..."
    validations:
      required: true

  - type: textarea
    id: error_message
    attributes:
      label: "Error Message Output"
      description: "Provide the error message or logs."
      placeholder: "Enter error message or logs here..."
    validations:
      required: true