// Generated by ferret kernel-extractor on 2026-06-02 from kernel.cu
// of workspace tag v003. Source workspace: /home/muhengl/ferret/workspace3.
// Mirage target task header:
//   /home/muhengl/mirage/include/mirage/persistent_kernel/tasks/blackwell/
//     fp8_gemm_dense_decode_splitk_sm100.cuh
// SOTA beaten: MPK in-tree fp8_gemm_dense_mediumm_sm100 at <128,NS=3,NE=4>
//   qkv_a_S2=1.07x, qkv_a_S4=1.14x, qkv_a_M4_S4=1.07x, o_proj_tripwire=1.00x
//   (mediumm@NS=3 baseline).
//
// New namespace: kernel::fp8_gemm_dense_qkva_splitk
// Distinct from kernel::fp8_gemm_dense_decode_splitk (red.add design,
// ws7/v001). This kernel uses the CORRECT race-free design:
//   exclusive FP32 partial slots + gen-tagged atomicAdd last-arriver +
//   fence.sc.gpu.
//
// B36 FIX (same as fp8_gemm_dense_decode_splitk_sm100.cuh):
//   Producer warp drives bf/be slot+parity from a continuous global k-tile
//   counter `gk` (not per-tile ki%NS + ph toggle), ensuring the pipeline
//   (slot,parity) stream is seamless across tile iterations regardless of
//   whether nk_slice % NS == 0.

#pragma once

#include <cstdint>
#include <cuda.h>
#include <cudaTypedefs.h>
#include <cuda_bf16.h>
#include <cuda_fp8.h>
#include <cuda_runtime.h>

namespace kernel {
namespace fp8_gemm_dense_qkva_splitk {

// Inter-CTA ordering fence for the last-arriver reduction. Default is the
// device-scope SC fence (fence.sc.gpu). Build with -DMPK_QKVA_SPLITK_V2_MEMBAR
// to substitute membar.gl (== __threadfence(), the NVIDIA threadFenceReduction
// idiom and the fence the working mediumm / group-GEMM kernels use). This is
// the A/B knob for the multi-rank deadlock investigation: fence.sc.gpu is a
// novel pattern in this tree and is the only inter-CTA-sync GEMM; every other
// GEMM uses membar.gl and runs clean at TP=4/EP=2 alongside NVSHMEM AllReduce.
#ifdef MPK_QKVA_SPLITK_V2_MEMBAR
#define MPK_QKVA_SPLITK_V2_FENCE() asm volatile("membar.gl;" ::: "memory")
#else
#define MPK_QKVA_SPLITK_V2_FENCE() asm volatile("fence.sc.gpu;" ::: "memory")
#endif

__device__ __forceinline__ uint32_t elect_one_sync_splitk() {
  uint32_t pred = 0;
  asm volatile("{\n\t.reg .pred %%px;\n\telect.sync _|%%px, %1;\n\t@%%px "
               "mov.s32 %0, 1;\n\t}"
               : "+r"(pred)
               : "r"(0xFFFFFFFF));
  return pred;
}

__device__ __forceinline__ void mb_init_sk(int a, int c) {
  asm volatile("mbarrier.init.shared::cta.b64 [%0], %1;" ::"r"(a), "r"(c));
}
__device__ __forceinline__ void mb_wait_sk(int a, int p) {
  asm volatile(
      "{\n\t.reg .pred "
      "P1;\n\tLW:\n\tmbarrier.try_wait.parity.acquire.cta.shared::cta.b64 P1, "
      "[%0], %1, %2;\n\t@P1 bra.uni DN;\n\tbra.uni LW;\n\tDN:\n\t}" ::"r"(a),
      "r"(p),
      "r"(0x989680));
}
__device__ __forceinline__ void mb_arrive_sk(int a) {
  asm volatile("mbarrier.arrive.release.cta.shared::cta.b64 _, [%0];" ::"r"(a)
               : "memory");
}
__device__ __forceinline__ void mb_arrive_tx_sk(int a, int s) {
  asm volatile(
      "mbarrier.arrive.expect_tx.release.cta.shared::cta.b64 _, [%0], %1;" ::
          "r"(a),
      "r"(s)
      : "memory");
}
__device__ __forceinline__ void
    tma_ld_sk(int d, void const *t, int x, int y, int m) {
  asm volatile("cp.async.bulk.tensor.2d.shared::cta.global.mbarrier::complete_"
               "tx::bytes [%0], [%1, {%2, %3}], [%4];" ::"r"(d),
               "l"(t),
               "r"(x),
               "r"(y),
               "r"(m)
               : "memory");
}

__device__ __forceinline__ constexpr uint64_t denc_sk(uint64_t x) {
  return (x & 0x3FFFFULL) >> 4ULL;
}
__device__ __forceinline__ uint64_t mkdesc_sk(int a) {
  return denc_sk(a) | (denc_sk(1024) << 32ULL) | (1ULL << 46ULL) |
         (2ULL << 61ULL);
}

// red_add_bf16x2: retained as a dead helper for ABI consistency; never called
// in the split-K epilogue (which uses the race-free FP32 partial design
// instead).
__device__ __forceinline__ void red_add_bf16x2(__nv_bfloat16 *ptr,
                                               uint32_t val) {
#if (defined(__CUDA_ARCH__) && (__CUDA_ARCH__ >= 900))
  asm volatile("red.relaxed.gpu.global.add.noftz.bf16x2 [%0], %1;" ::"l"(ptr),
               "r"(val)
               : "memory");
#else
  (void)ptr;
  (void)val;
#endif
}

// Inner persistent-task body. Templated so BN/NS/NE/SPLIT_K are compile-time.
// Called by fp8_gemm_dense_qkva_splitk_sm100_task_impl below.
//
// Reduction design (CORRECT — replaces crashed red.global.add.bf16x2):
//   Each K-slice CTA writes its FP32 partial to C_partial[ks][tile_id]
//   via direct store (exclusive slot). After all S partials are written,
//   the last arriver (gen-tagged atomicAdd on arrive_cnt[tile_id]) reduces
//   in FP32, casts once to BF16, and stores to C via vectorized st.v4.b32.
//   fence.sc.gpu (device-scope SC fence) before last-arriver reads and after
//   writing C guarantees inter-CTA ordering without membar.gl (L1-only).
//
// v003 improvement: vectorized last-arriver C-write (2x st.v4.b32 per 16 cols)
//   eliminated the scalar 2-byte store bottleneck (+45us S2 / +58us S4 in
//   v002). Column-major partial layout (v002): offset n*BM+et for coalesced
//   access.
//
// EXT_REDUCE (2026-06-02, external-reduce / race-free-by-construction design):
//   When EXT_REDUCE==true and SPLIT_K>1 each K-slice CTA writes ONLY its
//   exclusive FP32 partial slot and returns — NO bar.sync-3/4/5, NO arrive_cnt
//   atomicAdd, NO fence.sc.gpu, NO in-kernel last-arriver reduction. A SEPARATE
//   event-gated reduce task (TASK_FP8_GEMM_DENSE_SPLITK_REDUCE_SM100) — which
//   MPK's event system runs only AFTER all SPLIT_K GEMM CTAs for this tile
//   complete — sums the SPLIT_K partials in FP32 and casts to BF16. This
//   removes the inter-CTA last-arriver concurrency Heisenbug entirely
//   (correct ordering is enforced by the task DAG, not by atomics). C_partial
//   is then full-precision FP32 with NO reuse-within-a-tile, so no gen-tag is
//   needed. arrive_cnt is unused on this path (caller may pass nullptr).
template <int BN, int NS, int NE, int SPLIT_K, bool EXT_REDUCE = false>
__device__ __forceinline__ void
    task_impl_splitk_tpl(CUtensorMap const *ta_ptr,
                         CUtensorMap const *tb_ptr,
                         float const *__restrict__ sa,
                         float const *__restrict__ sb,
                         __nv_bfloat16 *__restrict__ C,
                         float *__restrict__ C_partial,
                         uint64_t *__restrict__ arrive_cnt,
                         int const M,
                         int const N,
                         int const K,
                         int const worker_idx,
                         int const num_workers) {
#if (defined(__CUDA_ARCH__) && (__CUDA_ARCH__ >= 1000))
  constexpr int BM = 128, BK = 128, UK = 32;
  static_assert(SPLIT_K >= 1, "SPLIT_K must be >= 1");
  int const tid = threadIdx.x, wid = tid / 32;
  int const nn = (N + BN - 1) / BN, nk = (K + BK - 1) / BK;
  // nk MUST be divisible by SPLIT_K (caller asserts at registration).
  int const nk_slice = nk / SPLIT_K;
  int const mm = (M + BM - 1) / BM;
  int const total = mm * nn * SPLIT_K;

  // Idle-CTA early-exit (mirrors fp8_gemm_dense_sm100_common.cuh's mediumm
  // path). When the persistent runtime dispatches more task instances than
  // there are output tiles (worker_idx >= total, e.g. at decode M=1 ->
  // total=mm*nn*SPLIT_K but the megakernel launches num_workers CTAs), the
  // surplus CTAs have no tile. They MUST skip the entire mbarrier-init +
  // tcgen05.alloc + __syncthreads + warp-role loops + membar.gl +
  // tcgen05.dealloc scaffold: an idle CTA that runs tcgen05.alloc holds a
  // tensor-memory allocation (TCA columns) and sits on the SM until its tail
  // dealloc, needlessly contending for the limited per-SM tensor-memory pool
  // and SM residency with the CTAs that DO have work. The branch is uniform
  // across all 256 threads (worker_idx + total are CTA-uniform), so the early
  // return is divergence-safe. mediumm has carried this since 2026-05-26; the
  // split-K kernel was missing it.
  if (worker_idx >= total) {
    return;
  }

  extern __shared__ __align__(1024) uint8_t sm_raw_fp8gemm_sk[];
  // Broadcast slot for last-arriver election among the 4 epilogue warps.
  __shared__ int s_is_last_sk;
  int sb_base = __cvta_generic_to_shared(sm_raw_fp8gemm_sk);
  int sb_aligned = (sb_base + 1023) & ~1023;

  constexpr int SA = BM * BK, SB = BN * BK;
  auto sA = [&](int s) { return sb_aligned + s * SA; };
  auto sBl = [&](int s) { return sb_aligned + NS * SA + s * SB; };

  int bars_addr = sb_aligned + NS * (SA + SB);
  int bf = bars_addr;
  int be = bf + NS * 8;
  int btf = be + NS * 8;
  int bte = btf + NE * 8;
  int tp_addr = bars_addr + (NS * 2 + NE * 2) * 8;
  constexpr int TC = NE * BN;
  constexpr int TCA = TC <= 32    ? 32
                      : TC <= 64  ? 64
                      : TC <= 128 ? 128
                      : TC <= 256 ? 256
                                  : 512;

  if (wid == 0 && elect_one_sync_splitk()) {
    asm volatile("prefetch.tensormap [%0];" ::"l"(ta_ptr));
    asm volatile("prefetch.tensormap [%0];" ::"l"(tb_ptr));
  }
  if (wid == 1 && elect_one_sync_splitk()) {
    for (int i = 0; i < NS; i++) {
      mb_init_sk(bf + i * 8, 1);
      mb_init_sk(be + i * 8, 1);
    }
    for (int i = 0; i < NE; i++) {
      mb_init_sk(btf + i * 8, 1);
      mb_init_sk(bte + i * 8, 128);
    }
    asm volatile("fence.mbarrier_init.release.cluster;");
  } else if (wid == 2) {
    asm volatile(
        "tcgen05.alloc.cta_group::1.sync.aligned.shared::cta.b32 [%0], %1;" ::
            "r"(tp_addr),
        "r"(TCA));
  }
  __syncthreads();
  uint32_t taddr;
  asm volatile("ld.shared.u32 %0, [%1];" : "=r"(taddr) : "r"(tp_addr));
  constexpr uint32_t idesc =
      (1u << 4) | ((uint32_t)(BN / 8) << 17) | (8u << 24);

  if (wid == 0 && elect_one_sync_splitk()) {
    // PRODUCER (TMA loader). FIX: continuous global k-tile counter `gk` drives
    // the bf/be slot+parity so the pipeline is seamless across tile iters
    // regardless of nk_slice % NS.
    int gk = 0;
    for (int iter = 0;; iter++) {
      int bidx = iter * num_workers + worker_idx;
      if (bidx >= total) {
        break;
      }
      // Tile decomposition: bidx -> (k_slice, bm, bn). k_slice outermost so
      // adjacent CTAs in a wave share (m,n) tiles and accumulate via reduce-add
      // into the same output region.
      int ks = bidx / (mm * nn);
      int rem = bidx % (mm * nn);
      int bm = rem / nn, bn = rem % nn;
      int om = bm * BM, on = bn * BN;
      int ki_base = ks * nk_slice; // global K-tile offset for this slice
      for (int ki = 0; ki < nk_slice; ki++, gk++) {
        int s = gk % NS;
        int ph = (gk / NS) & 1;
        mb_wait_sk(be + s * 8, ph ^ 1);
        int as_ = sA(s);
        int bs_ = sBl(s);
        int mb = bf + s * 8;
        tma_ld_sk(as_, ta_ptr, (ki_base + ki) * BK, om, mb);
        tma_ld_sk(bs_, tb_ptr, (ki_base + ki) * BK, on, mb);
        mb_arrive_tx_sk(mb, SA + SB);
      }
    }
  } else if (wid == 1 && elect_one_sync_splitk()) {
    // MMA issue. FIX: drive bf consumer slot+parity from the already-continuous
    // `gki` (was a per-iter `ki%NS` + `ph` that desynced on multi-wave).
    int gki = 0;
    for (int iter = 0;; iter++) {
      int bidx = iter * num_workers + worker_idx;
      if (bidx >= total) {
        break;
      }
      for (int ki = 0; ki < nk_slice; ki++, gki++) {
        int s = gki % NS;
        int php = (gki / NS) & 1;
        mb_wait_sk(bf + s * 8, php);
        int ai = gki % NE;
        int ap = (gki / NE) & 1;
        mb_wait_sk(bte + ai * 8, ap ^ 1);
        asm volatile("tcgen05.fence::after_thread_sync;");
        int as_ = sA(s);
        int bs_ = sBl(s);
        uint32_t tc = taddr + ai * BN;
        for (int k = 0; k < BK / UK; k++) {
          uint64_t ad = mkdesc_sk(as_ + k * UK), bd = mkdesc_sk(bs_ + k * UK);
          uint32_t en = (k > 0) ? 1u : 0u;
          asm volatile("{\n\t.reg .pred p;\n\tsetp.ne.b32 p, %4, "
                       "0;\n\ttcgen05.mma.cta_group::1.kind::f8f6f4 [%0], %1, "
                       "%2, %3, {%5, %6, %7, %8}, p;\n\t}\n" ::"r"(tc),
                       "l"(ad),
                       "l"(bd),
                       "r"(idesc),
                       "r"(en),
                       "r"(0u),
                       "r"(0u),
                       "r"(0u),
                       "r"(0u));
        }
        asm volatile("tcgen05.fence::before_thread_sync;");
        asm volatile("tcgen05.commit.cta_group::1.mbarrier::arrive::one.shared:"
                     ":cluster.b64 [%0];" ::"r"(be + s * 8)
                     : "memory");
        asm volatile("tcgen05.commit.cta_group::1.mbarrier::arrive::one.shared:"
                     ":cluster.b64 [%0];" ::"r"(btf + ai * 8)
                     : "memory");
      }
    }
  } else if (wid >= 4) {
    // EPILOGUE. gki already continuous (correct in the reference); acc[] reset
    // per tile iteration. Output via red.add (SPLIT_K>1) into pre-zeroed C.
    int const et = tid - 128, ew = wid - 4;
    int gki = 0;
    for (int iter = 0;; iter++) {
      int bidx = iter * num_workers + worker_idx;
      if (bidx >= total) {
        break;
      }
      int ks = bidx / (mm * nn);
      int rem = bidx % (mm * nn);
      int bm = rem / nn, bn = rem % nn;
      int om = bm * BM, on = bn * BN;
      int mi = om + et;
      int ki_base = ks * nk_slice;

      float acc[BN];
#pragma unroll
      for (int i = 0; i < BN; i++) {
        acc[i] = 0.0f;
      }

      for (int ki = 0; ki < nk_slice; ki++, gki++) {
        int kg = ki_base + ki; // global K-tile index for scale arrays
        float sfa = (mi < M) ? __ldg(sa + mi * nk + kg) : 0.0f;
        float sfb0 = __ldg(sb + (on / 128) * nk + kg);
        float sfb1 = 0.0f;
        if (BN > 128) {
          sfb1 = __ldg(sb + ((on + 128) / 128) * nk + kg);
        }

        int ai = gki % NE;
        int ap = (gki / NE) & 1;
        mb_wait_sk(btf + ai * 8, ap);
        asm volatile("tcgen05.fence::after_thread_sync;");

        float sf0 = sfa * sfb0, sf1 = sfa * sfb1;
#pragma unroll
        for (int i = 0; i < BN / 16; i++) {
          uint32_t ta_ = taddr + ((ew * 32) << 16) + ai * BN + i * 16;
          float v[16];
          asm volatile(
              "tcgen05.ld.sync.aligned.32x32b.x16.b32 "
              "{%0,%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15}, [%16];"
              : "=f"(v[0]),
                "=f"(v[1]),
                "=f"(v[2]),
                "=f"(v[3]),
                "=f"(v[4]),
                "=f"(v[5]),
                "=f"(v[6]),
                "=f"(v[7]),
                "=f"(v[8]),
                "=f"(v[9]),
                "=f"(v[10]),
                "=f"(v[11]),
                "=f"(v[12]),
                "=f"(v[13]),
                "=f"(v[14]),
                "=f"(v[15])
              : "r"(ta_));
          asm volatile("tcgen05.wait::ld.sync.aligned;");
          float sf = (BN <= 128 || i * 16 < 128) ? sf0 : sf1;
#pragma unroll
          for (int j = 0; j < 16; j++) {
            acc[i * 16 + j] += v[j] * sf;
          }
        }
        asm volatile("tcgen05.fence::before_thread_sync;");
        mb_arrive_sk(bte + ai * 8);
      }

      // ============== Split-K race-free reduction epilogue ==============
      // Replaces the crashed red.global.add.bf16x2-into-pre-zeroed-C design.
      // Each K-slice CTA writes its FP32 partial to an EXCLUSIVE slot; the
      // last arriver (gen-tagged atomicAdd) reduces in FP32 and writes C.
      if constexpr (SPLIT_K > 1) {
        size_t const tile_sz = (size_t)BM * BN;
        size_t const slice_sz = (size_t)mm * nn * tile_sz;
        int const tile_id = bm * nn + bn;
        // (1) Exclusive partial write. COLUMN-MAJOR within the tile
        //     (offset n*BM + et): for a fixed col n, threads et=0..127 write
        //     consecutive addresses -> fully coalesced 512B transactions.
        //     (Row-major et*BN+n strides adjacent threads 128 floats apart =
        //     one cache line per thread = the v001 reduction bottleneck.)
        if (mi < M) {
          float *pslot =
              C_partial + (size_t)ks * slice_sz + (size_t)tile_id * tile_sz;
#pragma unroll
          for (int n = 0; n < BN; n++) {
            pslot[(size_t)n * BM + et] = acc[n];
          }
        }
        // (2) Barrier: all 128 partial-row writes complete (intra-CTA commit).
        asm volatile("bar.sync 1, 128;");
        // EXT_REDUCE: this CTA's exclusive FP32 partial is now committed. The
        // event-gated reduce task (gated by the task DAG on ALL split-k GEMM
        // CTAs of this tile) does the FP32 sum + BF16 cast. Skip the in-kernel
        // last-arriver block entirely (no arrive_cnt, no SC fence, no race).
        // No membar.gl needed for cross-task visibility: persistent_kernel.cuh
        // issues a release fence + event bump at task completion that the
        // reduce task's wait acquires, so the partial writes are visible to the
        // reduce.
        // RETIRED 2026-06-03: the in-kernel last-arriver reduction below
        // (gen-tagged election + bare fence.sc.gpu + plain-load atomicAdd) was
        // a novel-to-the-tree hand-rolled inter-CTA reduction MISSING the
        // acquire/release pairing — it raced/IMA'd at multi-rank decode (a
        // Heisenbug). Design-A (external event-DAG-ordered reduce task,
        // fp8_gemm_dense_splitk_reduce_sm100.cuh, enum-323) is now the ONLY
        // split-K reduction path. EXT_REDUCE is forced true at every call site
        // (both public entry points route here with EXT_REDUCE=true), so this
        // branch is unconditionally taken and the dead last-arriver code below
        // is compiled out. arrive_cnt is unused (callers pass nullptr).
        if constexpr (EXT_REDUCE) {
          continue;
        }
#if 0 // RETIRED buggy in-kernel last-arriver reduction (see note above).
      // (3) ONE thread issues the device-scope SC fence (orders this CTA's
      //     partial writes globally) then the gen-tagged atomicAdd. v001
      //     issued the fence from all 128 epilogue threads (~45us tail);
      //     1/CTA is the standard last-block-reduction idiom — the barrier
      //     commits the 128 writes, the single SC fence drains device-wide.
        if (et == 0) {
          MPK_QKVA_SPLITK_V2_FENCE();
          unsigned long long old =
              atomicAdd((unsigned long long *)(arrive_cnt + tile_id), 1ULL);
          s_is_last_sk =
              ((old & 0xFFFFFFFFULL) == (unsigned long long)(SPLIT_K - 1)) ? 1
                                                                           : 0;
#ifdef MPK_QKVA_SPLITK_V2_DEBUG
          printf("[QKVA_V2 ARRIVE] wkr=%d ks=%d tile=%d old=%llu low32=%llu "
                 "elect=%d SPLIT_K=%d\n",
                 worker_idx,
                 ks,
                 tile_id,
                 old,
                 (old & 0xFFFFFFFFULL),
                 s_is_last_sk,
                 SPLIT_K);
#endif
        }
        asm volatile("bar.sync 1, 128;");
        // (5) Last-arriver reduces SPLIT_K partials in FP32, casts to BF16.
        if (s_is_last_sk) {
          // acquire: one SC fence makes all sibling K-slice partials visible,
          // then a barrier releases the 128 reducer threads.
          if (et == 0) {
            MPK_QKVA_SPLITK_V2_FENCE();
          }
          asm volatile("bar.sync 1, 128;");
          if (mi < M) {
            __nv_bfloat16 *row = C + (long long)mi * N + on;
            // Column-major base for this (tile, row): element n is at +n*BM.
            float const *pbase =
                C_partial + (size_t)tile_id * tile_sz + (size_t)et;
#pragma unroll
            for (int n = 0; n < BN; n += 16) {
              // Coalesced FP32 reads of S partials, fixed-order accumulate.
              float a[16];
#pragma unroll
              for (int j = 0; j < 16; j++) {
                float sum = 0.0f;
#pragma unroll
                for (int s2 = 0; s2 < SPLIT_K; s2++) {
                  sum += pbase[(size_t)s2 * slice_sz + (size_t)(n + j) * BM];
                }
                a[j] = sum;
              }
              if (on + n + 15 < N) {
                // Vectorized bf16 store (mirrors the SPLIT_K==1 fast path):
                // 8 bf16x2 packed into 2x st.v4.b32 (16B each) — vs the v002
                // scalar 2-byte stores that cost +45us(S2)/+58us(S4).
                nv_bfloat162 b0 = __floats2bfloat162_rn(a[0], a[1]);
                nv_bfloat162 b1 = __floats2bfloat162_rn(a[2], a[3]);
                nv_bfloat162 b2 = __floats2bfloat162_rn(a[4], a[5]);
                nv_bfloat162 b3 = __floats2bfloat162_rn(a[6], a[7]);
                nv_bfloat162 b4 = __floats2bfloat162_rn(a[8], a[9]);
                nv_bfloat162 b5 = __floats2bfloat162_rn(a[10], a[11]);
                nv_bfloat162 b6 = __floats2bfloat162_rn(a[12], a[13]);
                nv_bfloat162 b7 = __floats2bfloat162_rn(a[14], a[15]);
                uint32_t r0 = *reinterpret_cast<uint32_t *>(&b0);
                uint32_t r1 = *reinterpret_cast<uint32_t *>(&b1);
                uint32_t r2 = *reinterpret_cast<uint32_t *>(&b2);
                uint32_t r3 = *reinterpret_cast<uint32_t *>(&b3);
                uint32_t r4 = *reinterpret_cast<uint32_t *>(&b4);
                uint32_t r5 = *reinterpret_cast<uint32_t *>(&b5);
                uint32_t r6 = *reinterpret_cast<uint32_t *>(&b6);
                uint32_t r7 = *reinterpret_cast<uint32_t *>(&b7);
                asm volatile(
                    "st.relaxed.cta.global.L1::no_allocate.v4.b32 [%0], "
                    "{%1,%2,%3,%4};" ::"l"(row + n),
                    "r"(r0),
                    "r"(r1),
                    "r"(r2),
                    "r"(r3)
                    : "memory");
                asm volatile(
                    "st.relaxed.cta.global.L1::no_allocate.v4.b32 [%0], "
                    "{%1,%2,%3,%4};" ::"l"(row + n + 8),
                    "r"(r4),
                    "r"(r5),
                    "r"(r6),
                    "r"(r7)
                    : "memory");
              } else {
                for (int j = 0; j < 16 && on + n + j < N; j++) {
                  row[n + j] = __float2bfloat16(a[j]);
                }
              }
            }
          }
          // release: barrier so all C writes are issued, then ONE SC fence
          // makes the final BF16 result globally visible + bumps generation.
          asm volatile("bar.sync 1, 128;");
          if (et == 0) {
            MPK_QKVA_SPLITK_V2_FENCE();
            arrive_cnt[tile_id] = ((arrive_cnt[tile_id] >> 32) + 1ULL) << 32;
#ifdef MPK_QKVA_SPLITK_V2_DEBUG
            printf(
                "[QKVA_V2 BUMP  ] wkr=%d ks=%d tile=%d new_arrive_cnt=%llu\n",
                worker_idx,
                ks,
                tile_id,
                (unsigned long long)arrive_cnt[tile_id]);
#endif
          }
        }
        asm volatile("bar.sync 1, 128;"); // order gen bump before tile reuse
#endif // RETIRED buggy in-kernel last-arriver reduction
      } else if (mi < M) {
        // SPLIT_K == 1: direct store (o_proj_tripwire path), unchanged.
        __nv_bfloat16 *row = C + (long long)mi * N + on;
#pragma unroll
        for (int n = 0; n < BN; n += 16) {
          if (on + n + 15 < N) {
            nv_bfloat162 b0 = __floats2bfloat162_rn(acc[n + 0], acc[n + 1]);
            nv_bfloat162 b1 = __floats2bfloat162_rn(acc[n + 2], acc[n + 3]);
            nv_bfloat162 b2 = __floats2bfloat162_rn(acc[n + 4], acc[n + 5]);
            nv_bfloat162 b3 = __floats2bfloat162_rn(acc[n + 6], acc[n + 7]);
            nv_bfloat162 b4 = __floats2bfloat162_rn(acc[n + 8], acc[n + 9]);
            nv_bfloat162 b5 = __floats2bfloat162_rn(acc[n + 10], acc[n + 11]);
            nv_bfloat162 b6 = __floats2bfloat162_rn(acc[n + 12], acc[n + 13]);
            nv_bfloat162 b7 = __floats2bfloat162_rn(acc[n + 14], acc[n + 15]);
            uint32_t r0 = *reinterpret_cast<uint32_t *>(&b0);
            uint32_t r1 = *reinterpret_cast<uint32_t *>(&b1);
            uint32_t r2 = *reinterpret_cast<uint32_t *>(&b2);
            uint32_t r3 = *reinterpret_cast<uint32_t *>(&b3);
            uint32_t r4 = *reinterpret_cast<uint32_t *>(&b4);
            uint32_t r5 = *reinterpret_cast<uint32_t *>(&b5);
            uint32_t r6 = *reinterpret_cast<uint32_t *>(&b6);
            uint32_t r7 = *reinterpret_cast<uint32_t *>(&b7);
            asm volatile("st.relaxed.cta.global.L1::no_allocate.v4.b32 [%0], "
                         "{%1,%2,%3,%4};" ::"l"(row + n),
                         "r"(r0),
                         "r"(r1),
                         "r"(r2),
                         "r"(r3)
                         : "memory");
            asm volatile("st.relaxed.cta.global.L1::no_allocate.v4.b32 [%0], "
                         "{%1,%2,%3,%4};" ::"l"(row + n + 8),
                         "r"(r4),
                         "r"(r5),
                         "r"(r6),
                         "r"(r7)
                         : "memory");
          } else {
            for (int j = 0; j < 16 && on + n + j < N; j += 2) {
              if (on + n + j + 1 < N) {
                nv_bfloat162 b =
                    __floats2bfloat162_rn(acc[n + j], acc[n + j + 1]);
                uint32_t r = *reinterpret_cast<uint32_t *>(&b);
                *reinterpret_cast<uint32_t *>(row + n + j) = r;
              } else {
                row[n + j] = __float2bfloat16(acc[n + j]);
              }
            }
          }
        }
      }
    }
  }

  __syncthreads();
  asm volatile("membar.gl;" ::: "memory");
  if (wid == 0) {
    asm volatile(
        "tcgen05.dealloc.cta_group::1.sync.aligned.b32 %0, %1;" ::"r"(taddr),
        "r"(TCA));
  }
#endif
}

// Public __device__ __noinline__ entry point matching the Mirage task ABI.
// Instantiate at <BN=128, NS=3, NE=2, SPLIT_K=2> and <BN=128, NS=3, NE=2,
// SPLIT_K=4>.
//
// RETIRED 2026-06-03: this entry point used to route to the in-kernel
// last-arriver reduction (EXT_REDUCE=false). That path raced at multi-rank
// decode and has been removed (see task_impl_splitk_tpl). It now routes to the
// SAME race-free Design-A write-partials path as the *_extred entry point
// (EXT_REDUCE=true): the K-slice CTAs write ONLY their exclusive FP32 partials
// and a separate event-gated reduce task (enum-323) does the FP32 sum + BF16
// cast. The builder no longer calls this entry point for split-K>1 (it uses the
// *_extred path); this stub is kept only for ABI/signature compatibility and is
// now race-free for any caller. `arrive_cnt` is unused (ignored).
template <int BN, int NS, int NE, int SPLIT_K>
__device__ __noinline__ void fp8_gemm_dense_qkva_splitk_sm100_task_impl(
    CUtensorMap const *ta_ptr,
    CUtensorMap const *tb_ptr,
    float const *__restrict__ sa,
    float const *__restrict__ sb,
    __nv_bfloat16 *__restrict__ C,
    float *__restrict__ C_partial,
    uint64_t *__restrict__ arrive_cnt,
    int const M,
    int const N,
    int const K,
    int const worker_idx,
    int const num_workers) {
  (void)arrive_cnt; // retired in-kernel last-arriver no longer uses this
  task_impl_splitk_tpl<BN, NS, NE, SPLIT_K, /*EXT_REDUCE=*/true>(ta_ptr,
                                                                 tb_ptr,
                                                                 sa,
                                                                 sb,
                                                                 C,
                                                                 C_partial,
                                                                 /*arrive_cnt=*/
                                                                 nullptr,
                                                                 M,
                                                                 N,
                                                                 K,
                                                                 worker_idx,
                                                                 num_workers);
}

// External-reduce entry point. K-slice CTAs write ONLY their exclusive FP32
// partials into C_partial; a SEPARATE event-gated reduce task does the FP32
// sum + BF16 cast (see fp8_gemm_dense_splitk_reduce_sm100.cuh). No arrive_cnt,
// no in-kernel last-arriver, no inter-CTA atomics — race-free by construction.
// `C` is left untouched here (the reduce task writes the final BF16 output).
template <int BN, int NS, int NE, int SPLIT_K>
__device__ __noinline__ void fp8_gemm_dense_qkva_splitk_extred_sm100_task_impl(
    CUtensorMap const *ta_ptr,
    CUtensorMap const *tb_ptr,
    float const *__restrict__ sa,
    float const *__restrict__ sb,
    __nv_bfloat16 *__restrict__ C,
    float *__restrict__ C_partial,
    int const M,
    int const N,
    int const K,
    int const worker_idx,
    int const num_workers) {
  task_impl_splitk_tpl<BN, NS, NE, SPLIT_K, /*EXT_REDUCE=*/true>(ta_ptr,
                                                                 tb_ptr,
                                                                 sa,
                                                                 sb,
                                                                 C,
                                                                 C_partial,
                                                                 /*arrive_cnt=*/
                                                                 nullptr,
                                                                 M,
                                                                 N,
                                                                 K,
                                                                 worker_idx,
                                                                 num_workers);
}

// Shared-memory size helper for use by mpk_runtime at kernel registration.
// Formula: NS*(BM*BK + BN*BK) + (NS*2 + NE*2)*8 + 8 + 1024
template <int BN, int NS, int NE, int SPLIT_K>
__host__ __device__ inline constexpr int
    fp8_gemm_dense_qkva_splitk_smem_size() {
  constexpr int BM = 128, BK = 128;
  return NS * (BM * BK + BN * BK) + (NS * 2 + NE * 2) * 8 + 8 + 1024;
}

} // namespace fp8_gemm_dense_qkva_splitk
} // namespace kernel
