// Generated by ferret kernel-extractor on 2026-06-13 from kernel.cu
// of workspace tag v002. Source workspace: workspace1.
// Mirage target task header:
//   /home/muhengl/mirage/include/mirage/persistent_kernel/tasks/blackwell/fp8_gemm_dense_smallm_sm100.cuh
// SOTA beaten: in-tree fp8_gemm_dense_smallm<BN=128,NS=6,NE=2> at
//   qkv_a_M1=173.6%, q_b_M1=139.8%; best-effort gate_up_M1=128.6%.
//
// NOTE FOR MIRAGE MAIN AGENT (raw-pointer-in-TMA-slot convention):
//   This kernel is a CUDA-core GEMV; it does NOT use TMA descriptors.
//   ta_ptr and tb_ptr carry raw device pointers (reinterpret_cast to
//   CUtensorMap const*) for A and B respectively. The dispatcher must
//   pass buf.dA / buf.dB cast to CUtensorMap*, NOT a tensormap struct
//   address. This requires either a new TASK_FP8_GEMM_DENSE_GEMV_M1_SM100
//   task type routing A/B through input_ptrs[] slots, or accepting the
//   raw-pointer convention in the wiring layer. The kernel itself is
//   correct and crash-safe (no tcgen05, no mbarrier, no TMEM).

#pragma once

#include <cuda.h>
#include <cudaTypedefs.h>
#include <cuda_bf16.h>
#include <cuda_fp8.h>
#include <cuda_runtime.h>

namespace kernel {
namespace fp8_gemm_dense_gemv_m1 {

// ---- Device helpers -------------------------------------------------------

__device__ __forceinline__ float fp8_to_f(unsigned char b) {
  return __half2float(__nv_cvt_fp8_to_halfraw((__nv_fp8_storage_t)b, __NV_E4M3));
}

// Dot product of 16 FP8 values packed in one uint4 (a) against one uint4 (b).
__device__ __forceinline__ float dot16(uint4 a, uint4 b) {
  float s = 0.f;
  uint32_t av[4] = {a.x, a.y, a.z, a.w};
  uint32_t bv[4] = {b.x, b.y, b.z, b.w};
#pragma unroll
  for (int i = 0; i < 4; i++) {
    uint32_t aw = av[i], bw = bv[i];
    s += fp8_to_f(aw & 0xff) * fp8_to_f(bw & 0xff);
    s += fp8_to_f((aw >> 8) & 0xff) * fp8_to_f((bw >> 8) & 0xff);
    s += fp8_to_f((aw >> 16) & 0xff) * fp8_to_f((bw >> 16) & 0xff);
    s += fp8_to_f((aw >> 24) & 0xff) * fp8_to_f((bw >> 24) & 0xff);
  }
  return s;
}

// Warp-reduce sum across all 32 lanes.
__device__ __forceinline__ float warp_sum(float v) {
#pragma unroll
  for (int o = 16; o > 0; o >>= 1)
    v += __shfl_down_sync(0xffffffffu, v, o);
  return v;
}

// ---- SMEM size helper (host + device callable) ----------------------------

// Returns required dynamic shared memory in bytes for a given K.
// BN = output columns per CTA; NS = warps-per-column (WPC, intra-CTA K-split).
template <int BN, int NS>
__host__ __device__ inline constexpr int fp8_gemm_dense_gemv_m1_smem_size(int K) {
  return ((K + 15) & ~15) + (K >> 7) * 4 + BN * NS * 4 + 16;
}

// ---- Main task function ---------------------------------------------------
//
// Signature mirrors fp8_gemm_dense_smallm_sm100_task_impl<BN,NS> exactly
// (same 11 parameters, same order, same types) so it can serve as a
// drop-in for MPK's TASK_FP8_GEMM_DENSE_SM100 after Mirage-side wiring
// of the raw-pointer convention (see file header note).
//
// BN  = output columns per CTA (= warps per CTA when WPC=1; = BN/NS columns
//       otherwise). blockDim.x must equal BN * NS * 32.
// NS  = warps-per-column (WPC): intra-CTA K-split used to raise SM occupancy
//       at small-N configs where warp-per-column alone leaves SMs starved.
//
// ta_ptr: raw FP8 device pointer for A[1, K] (reinterpret_cast from void*).
// tb_ptr: raw FP8 device pointer for B[N, K] (reinterpret_cast from void*).
// sa:     per-group activation scale, shape [1, K/128], row-major.
// sb:     per-group weight scale, shape [N/128, K/128], row-major.
// C:      output BF16 vector [1, N].
// M:      must be 1 (GEMV); parameter kept for ABI compatibility.
// N:      total number of output columns.
// K:      inner dimension.
// worker_idx:   this CTA's persistent-kernel worker index.
// num_workers:  total number of persistent-kernel workers (grid size).
// C_row_stride: unused for M=1; retained for ABI compatibility.

template <int BN, int NS>
__device__ __noinline__ void fp8_gemm_dense_gemv_m1_sm100_task_impl(
    CUtensorMap const *ta_ptr,
    CUtensorMap const *tb_ptr,
    float const *__restrict__ sa,
    float const *__restrict__ sb,
    __nv_bfloat16 *__restrict__ C,
    int const M,
    int const N,
    int const K,
    int const worker_idx,
    int const num_workers,
    int const C_row_stride = -1) {
  (void)M;
  (void)C_row_stride;
  constexpr int WPC = NS;
  unsigned char const *Ag = reinterpret_cast<unsigned char const *>(ta_ptr);
  unsigned char const *Bg = reinterpret_cast<unsigned char const *>(tb_ptr);
  int const nk     = K >> 7;   // K / 128 groups
  int const nchunk = K >> 9;   // K / 512  (32 lanes * 16 bytes each)
  int const tid    = threadIdx.x;
  int const lane   = tid & 31;
  int const warpId = tid >> 5;
  int const c      = warpId / WPC;   // column index within CTA (0..BN-1)
  int const sw     = warpId % WPC;   // sub-warp index over K-chunks (0..WPC-1)

  // SMEM layout:
  //   [0            .. K-1]         : A row (FP8, byte-per-element)
  //   [aligned(K)   .. +nk*4-1]    : sa[nk] (float32)
  //   [+nk*4        .. +BN*WPC*4-1]: intra-CTA reduction scratch (float32)
  extern __shared__ unsigned char smem[];
  unsigned char *A_s  = smem;
  float         *sa_s = reinterpret_cast<float *>(A_s + ((K + 15) & ~15));
  float         *red  = sa_s + nk;   // BN*WPC floats

  // Cooperative one-shot load of A[1,K] (vectorized u32) and sa[nk].
  uint32_t const *Ag32 = reinterpret_cast<uint32_t const *>(Ag);
  uint32_t       *A_s32 = reinterpret_cast<uint32_t *>(A_s);
  int const K4 = K >> 2;
  for (int i = tid; i < K4; i += blockDim.x)
    A_s32[i] = __ldg(Ag32 + i);
  for (int i = tid; i < nk; i += blockDim.x)
    sa_s[i] = __ldg(sa + i);
  __syncthreads();
  uint4 const *A_s4 = reinterpret_cast<uint4 const *>(A_s);

  // Persistent sweep over N-slices (BN output columns per CTA per slice).
  for (int slice = worker_idx; slice * BN < N; slice += num_workers) {
    int const col = slice * BN + c;
    if (col < N) {
      uint4  const *Brow4  = reinterpret_cast<uint4 const *>(Bg + (size_t)col * K);
      float  const *sb_row = sb + (size_t)(col >> 7) * nk;   // sb[col/128][.]
      float acc = 0.f;
#pragma unroll 4
      for (int ch = sw; ch < nchunk; ch += WPC) {
        int const u = (ch << 5) + lane;
        uint4 a = A_s4[u];
        uint4 b = __ldg(Brow4 + u);
        int const g = (ch << 2) + (lane >> 3);
        acc += dot16(a, b) * (sa_s[g] * __ldg(sb_row + g));
      }
      acc = warp_sum(acc);
      if (lane == 0)
        red[c * WPC + sw] = acc;
    }
    __syncthreads();
    if (sw == 0 && lane == 0 && col < N) {
      float s = 0.f;
#pragma unroll
      for (int w = 0; w < WPC; w++)
        s += red[c * WPC + w];
      C[col] = __float2bfloat16(s);
    }
    __syncthreads();   // red[] reused next slice
  }
}

} // namespace fp8_gemm_dense_gemv_m1
} // namespace kernel
