// Generated by ferret kernel-extractor on 2026-06-05 from kernel.cu
// of workspace tag v004. Source workspace: /home/muhengl/ferret/workspace3.
// Mirage target task header:
//   /home/muhengl/mirage/include/mirage/persistent_kernel/tasks/blackwell/
//     fp8_gemm_dense_splitk_tma_reduce_sm100.cuh
// SOTA beaten: MPK in-tree fp8_gemm_dense_mediumm (reference PERF BAR) at
//   qkv_a_SK8 1.601x, qkv_a_SK4 1.333x, gate_up_SK4 1.333x,
//   o_proj_tripwire 0.900x (tripwire target 1%, met).
//
// CRASH-SAFETY NOTE (workspace3, v004 low-TMEM design):
//   TCA = NE*MMA_N = 4*16 = 64 columns. Co-residency-safe: MLA-TP holds 512
//   total columns; 64 leaves 448-col headroom (OPT #2 directive verified).
//   Same-warp: warp 0 issues BOTH tcgen05.alloc AND tcgen05.dealloc.
//
// OPT #1 FORK NOTE: task_impl_low_tmem_tpl exposes a gflag/epoch pair that
// drives the k_slice==0-store / k_slice>0-reduce-add fork. The public
// fp8_gemm_dense_splitk_tma_reduce_sm100_task_impl passes gflag=nullptr so
// Mirage's MPK pre-zero (tensor_init) path is preserved. The standalone
// splitk_launch __global__ wires gflag to eliminate the pre-zero entirely.
// MPK can later adopt the fork by passing a per-tile arrival counter from
// the scheduler — the machinery is present and correct.
//
// NE=4 NOTE for Mirage agent: task_register.cc must be recompiled with NE=4
// (not the prior NE=2) when this header is adopted. The public ABI is
// unchanged (11 params); only the NE template parameter changes.

#pragma once

#include <cstdint>
#include <cuda.h>
#include <cudaTypedefs.h>
#include <cuda_bf16.h>
#include <cuda_fp8.h>
#include <cuda_runtime.h>

namespace kernel {
namespace fp8_gemm_dense_splitk_low_tmem {

// ---------------------------------------------------------------------------
// Device helpers — mbarrier, TMA load, descriptor encoding, TMA reduce-add,
// TMA plain store. All lifted verbatim from workspace3/kernel.cu tag v004
// (namespace-local, no external dependency).
// ---------------------------------------------------------------------------

__device__ __forceinline__ uint32_t elect_one_sync_lt() {
  uint32_t pred = 0;
  asm volatile("{\n\t.reg .pred %%px;\n\telect.sync _|%%px, %1;\n\t@%%px "
               "mov.s32 %0, 1;\n\t}"
               : "+r"(pred)
               : "r"(0xFFFFFFFF));
  return pred;
}

__device__ __forceinline__ void mb_init_lt(int a, int c) {
  asm volatile("mbarrier.init.shared::cta.b64 [%0], %1;" ::"r"(a), "r"(c));
}

__device__ __forceinline__ void mb_wait_lt(int a, int p) {
  asm volatile(
      "{\n\t.reg .pred "
      "P1;\n\tLW:\n\tmbarrier.try_wait.parity.acquire.cta.shared::cta.b64 P1, "
      "[%0], %1, %2;\n\t@P1 bra.uni DN;\n\tbra.uni LW;\n\tDN:\n\t}" ::"r"(a),
      "r"(p),
      "r"(0x989680));
}

__device__ __forceinline__ void mb_arrive_lt(int a) {
  asm volatile("mbarrier.arrive.release.cta.shared::cta.b64 _, [%0];" ::"r"(a)
               : "memory");
}

__device__ __forceinline__ void mb_arrive_tx_lt(int a, int s) {
  asm volatile(
      "mbarrier.arrive.expect_tx.release.cta.shared::cta.b64 _, [%0], %1;" ::
          "r"(a),
      "r"(s)
      : "memory");
}

__device__ __forceinline__ void
    tma_ld_lt(int d, void const *t, int x, int y, int m) {
  asm volatile("cp.async.bulk.tensor.2d.shared::cta.global.mbarrier::complete_"
               "tx::bytes [%0], [%1, {%2, %3}], [%4];" ::"r"(d),
               "l"(t),
               "r"(x),
               "r"(y),
               "r"(m)
               : "memory");
}

__device__ __forceinline__ constexpr uint64_t denc_lt(uint64_t x) {
  return (x & 0x3FFFFULL) >> 4ULL;
}

__device__ __forceinline__ uint64_t mkdesc_lt(int a) {
  return denc_lt(a) | (denc_lt(1024) << 32ULL) | (1ULL << 46ULL) |
         (2ULL << 61ULL);
}

// fence.proxy.async — generic SMEM stores visible to async (TMA) proxy before
// the bulk reduce reads them.
__device__ __forceinline__ void tma_store_fence_lt() {
  asm volatile("fence.proxy.async.shared::cta;" ::: "memory");
}

// 2D bf16 reduce-add: TMA atomically adds the SMEM tile into GMEM at {c0,c1}.
__device__ __forceinline__ void
    tma_reduce_add_2d(CUtensorMap const *desc, int smem_addr, int c0, int c1) {
  uint64_t d = reinterpret_cast<uint64_t>(desc);
  asm volatile("cp.reduce.async.bulk.tensor.2d.global.shared::cta.add.bulk_"
               "group [%0, {%2, %3}], [%1];" ::"l"(d),
               "r"(smem_addr),
               "r"(c0),
               "r"(c1)
               : "memory");
}

// 2D bf16 plain store: TMA OVERWRITES GMEM at {c0,c1} with the SMEM tile.
// Used by the k_slice==0 CTA in the store/reduce-add fork (OPT #1) so the
// output never needs a host-side pre-zero — k0 lays down the base, k>0 add.
__device__ __forceinline__ void
    tma_store_2d(CUtensorMap const *desc, int smem_addr, int c0, int c1) {
  uint64_t d = reinterpret_cast<uint64_t>(desc);
  asm volatile("cp.async.bulk.tensor.2d.global.shared::cta.bulk_group "
               "[%0, {%2, %3}], [%1];" ::"l"(d),
               "r"(smem_addr),
               "r"(c0),
               "r"(c1)
               : "memory");
}

__device__ __forceinline__ void tma_commit_lt() {
  asm volatile("cp.async.bulk.commit_group;" ::: "memory");
}

__device__ __forceinline__ void tma_wait_lt() {
  asm volatile("cp.async.bulk.wait_group 0;" ::: "memory");
}

// ---------------------------------------------------------------------------
// smem_size_low_tmem<BN,NS,NE,SPLIT_K>() — dynamic shared memory footprint.
// Called by the Mirage task dispatcher to set cudaFuncAttributeMaxDynamic
// SharedMemorySize. SPLIT_K is a dummy template param kept for ABI symmetry.
// ---------------------------------------------------------------------------
template <int BN, int NS, int NE, int SPLIT_K>
__host__ __device__ inline constexpr int smem_size_low_tmem() {
  constexpr int BM = 128, BK = 128;
  int compute = NS * (BM * BK + BN * BK) + (NS * 2 + NE * 2) * 8 + 8;
  int c_off = (compute + 1023) & ~1023;
  return c_off + BM * BN * 2 + 2048;
}

// ---------------------------------------------------------------------------
// task_impl_low_tmem_tpl — internal device function.
//
// gflag / epoch drive the OPT #1 store/reduce-add fork:
//   gflag == nullptr -> pure reduce-add into a pre-zeroed buffer (Mirage
//                       tensor_init path, backward-compat with Mirage ABI).
//   gflag != nullptr -> k_slice==0 CTAs do a plain TMA store (overwrite),
//                       then publish gflag[tile]=epoch; k_slice>0 CTAs spin
//                       until gflag[tile]>=epoch, then reduce-add. Eliminates
//                       the host/scheduler pre-zero entirely.
//
// The public fp8_gemm_dense_splitk_tma_reduce_sm100_task_impl always passes
// gflag=nullptr. The standalone splitk_launch __global__ (in kernel.cu only)
// passes the per-tile flag array.
// ---------------------------------------------------------------------------
template <int BN, int NS, int NE, int SPLIT_K>
__device__ __forceinline__ void
    task_impl_low_tmem_tpl(CUtensorMap const *ta_ptr,
                           CUtensorMap const *tb_ptr,
                           float const *__restrict__ sa,
                           float const *__restrict__ sb,
                           __nv_bfloat16 *__restrict__ C,
                           int const M,
                           int const N,
                           int const K,
                           int const worker_idx,
                           int const num_workers,
                           CUtensorMap const *tc_ptr,
                           int *gflag,
                           int epoch) {
#if (defined(__CUDA_ARCH__) && (__CUDA_ARCH__ >= 1000))
  constexpr int BM = 128, BK = 128, UK = 32;
  constexpr int MMA_N = 16;        // LOW-TMEM: MMA N tile width (not BN!)
  constexpr int NSUB = BN / MMA_N; // sub-tiles per BN=128 scheduler tile (=8)
  static_assert(SPLIT_K >= 1, "SPLIT_K must be >= 1");
  static_assert(BN % MMA_N == 0, "BN must be a multiple of MMA_N");
  int const tid = threadIdx.x, wid = tid / 32;
  int const nn = (N + BN - 1) / BN, nk = (K + BK - 1) / BK;
  int const nk_slice = nk / SPLIT_K;
  int const mm = (M + BM - 1) / BM;
  int const total = mm * nn * SPLIT_K;

  extern __shared__ __align__(1024) uint8_t sm_raw_lt[];
  int sb_base = __cvta_generic_to_shared(sm_raw_lt);
  int sb_aligned = (sb_base + 1023) & ~1023;

  constexpr int SA = BM * BK, SB = BN * BK; // full 128-wide A and B tiles
  auto sA = [&](int s) { return sb_aligned + s * SA; };
  auto sBl = [&](int s) { return sb_aligned + NS * SA + s * SB; };

  int bars_addr = sb_aligned + NS * (SA + SB);
  int bf = bars_addr;        // A/B full   (NS)
  int be = bf + NS * 8;      // A/B empty  (NS)
  int btf = be + NS * 8;     // TMEM scratch full  (NE)
  int bte = btf + NE * 8;    // TMEM scratch empty (NE)
  int tp_addr = bars_addr + (NS * 2 + NE * 2) * 8;
  // bf16 [BM][BN] output staging tile (row-major, no swizzle), 1024-aligned.
  int c_smem = (tp_addr + 8 + 1023) & ~1023;

  // LOW-TMEM: scratch width MMA_N (not BN). TC = NE*MMA_N = 64 columns (NE=4).
  constexpr int TC = NE * MMA_N;
  constexpr int TCA = TC <= 32    ? 32
                      : TC <= 64  ? 64
                      : TC <= 128 ? 128
                      : TC <= 256 ? 256
                                  : 512;

  // SAME-WARP TMEM PERMIT: warp 0 issues alloc AND dealloc (crash-free BF16
  // split-K pattern). Do the uniform alloc first, then warp 0's hint prefetch.
  if (wid == 0) {
    asm volatile(
        "tcgen05.alloc.cta_group::1.sync.aligned.shared::cta.b32 [%0], %1;" ::
            "r"(tp_addr),
        "r"(TCA));
    if (elect_one_sync_lt()) {
      asm volatile("prefetch.tensormap [%0];" ::"l"(ta_ptr));
      asm volatile("prefetch.tensormap [%0];" ::"l"(tb_ptr));
    }
  } else if (wid == 1 && elect_one_sync_lt()) {
    for (int i = 0; i < NS; i++) {
      mb_init_lt(bf + i * 8, 1);
      mb_init_lt(be + i * 8, 1);
    }
    for (int i = 0; i < NE; i++) {
      mb_init_lt(btf + i * 8, 1);
      mb_init_lt(bte + i * 8, 128);
    }
    asm volatile("fence.mbarrier_init.release.cluster;");
  }
  __syncthreads();
  uint32_t taddr;
  asm volatile("ld.shared.u32 %0, [%1];" : "=r"(taddr) : "r"(tp_addr));
  // MMA instruction descriptor: N field = MMA_N/8 (low-TMEM), not BN/8.
  constexpr uint32_t idesc =
      (1u << 4) | ((uint32_t)(MMA_N / 8) << 17) | (8u << 24);

  if (wid == 0 && elect_one_sync_lt()) {
    // PRODUCER — load full 128-wide A and B per K-tile (B sliced in the MMA
    // warp). Continuous gk counter (B36): seamless across multi-tile-iter.
    int gk = 0;
    for (int iter = 0;; iter++) {
      int bidx = iter * num_workers + worker_idx;
      if (bidx >= total) {
        break;
      }
      int ks = bidx / (mm * nn);
      int rem = bidx % (mm * nn);
      int bm = rem / nn, bn = rem % nn;
      int om = bm * BM, on = bn * BN;
      int ki_base = ks * nk_slice;
      for (int ki = 0; ki < nk_slice; ki++, gk++) {
        int s = gk % NS;
        int ph = (gk / NS) & 1;
        mb_wait_lt(be + s * 8, ph ^ 1);
        int as_ = sA(s);
        int bs_ = sBl(s);
        int mb = bf + s * 8;
        tma_ld_lt(as_, ta_ptr, (ki_base + ki) * BK, om, mb);
        tma_ld_lt(bs_, tb_ptr, (ki_base + ki) * BK, on, mb);
        mb_arrive_tx_lt(mb, SA + SB);
      }
    }
  } else if (wid == 1 && elect_one_sync_lt()) {
    // MMA — for each K-tile, issue NSUB sub-MMAs (each 128 x MMA_N) from the
    // resident A and a 16-col slice of B. TMEM scratch ping-pongs over the
    // continuous sub-step counter gs (NE buffers). bf/be track K-tiles (gkc).
    int gkc = 0; // K-tile counter (bf/be slot+parity)
    int gs = 0;  // sub-step counter (btf/bte slot+parity)
    for (int iter = 0;; iter++) {
      int bidx = iter * num_workers + worker_idx;
      if (bidx >= total) {
        break;
      }
      for (int ki = 0; ki < nk_slice; ki++, gkc++) {
        int s = gkc % NS;
        int php = (gkc / NS) & 1;
        mb_wait_lt(bf + s * 8, php); // A+B loaded for this K-tile
        int as_ = sA(s);
        int bs_ = sBl(s);
        for (int sub = 0; sub < NSUB; sub++, gs++) {
          int ai = gs % NE;
          int ap = (gs / NE) & 1;
          mb_wait_lt(bte + ai * 8, ap ^ 1); // scratch ai free
          asm volatile("tcgen05.fence::after_thread_sync;");
          uint32_t tc = taddr + ai * MMA_N;
          int bsub = bs_ + sub * MMA_N * BK; // 16-row slice of B in SMEM
          for (int k = 0; k < BK / UK; k++) {
            uint64_t ad = mkdesc_lt(as_ + k * UK),
                     bd = mkdesc_lt(bsub + k * UK);
            uint32_t en = (k > 0) ? 1u : 0u;
            asm volatile("{\n\t.reg .pred p;\n\tsetp.ne.b32 p, %4, "
                         "0;\n\ttcgen05.mma.cta_group::1.kind::f8f6f4 [%0], %1, "
                         "%2, %3, {%5, %6, %7, %8}, p;\n\t}\n" ::"r"(tc),
                         "l"(ad),
                         "l"(bd),
                         "r"(idesc),
                         "r"(en),
                         "r"(0u),
                         "r"(0u),
                         "r"(0u),
                         "r"(0u));
          }
          asm volatile("tcgen05.fence::before_thread_sync;");
          // tell epilogue scratch ai is ready
          asm volatile("tcgen05.commit.cta_group::1.mbarrier::arrive::one."
                       "shared::cluster.b64 [%0];" ::"r"(btf + ai * 8)
                       : "memory");
        }
        // release A+B buffer after all NSUB sub-MMAs consumed it
        asm volatile("tcgen05.commit.cta_group::1.mbarrier::arrive::one."
                     "shared::cluster.b64 [%0];" ::"r"(be + s * 8)
                     : "memory");
      }
    }
  } else if (wid >= 4) {
    // EPILOGUE — read each sub's 16-col scratch, dequant, accumulate the
    // K-running sum in registers acc[BN]. After all K-tiles, R2S + reduce-add.
    int const et = tid - 128, ew = wid - 4;
    int gs = 0; // sub-step counter (matches MMA gs)
    for (int iter = 0;; iter++) {
      int bidx = iter * num_workers + worker_idx;
      if (bidx >= total) {
        break;
      }
      int ks = bidx / (mm * nn);
      int rem = bidx % (mm * nn);
      int bm = rem / nn, bn = rem % nn;
      int om = bm * BM, on = bn * BN;
      int mi = om + et;
      int ki_base = ks * nk_slice;

      float acc[BN];
#pragma unroll
      for (int i = 0; i < BN; i++) {
        acc[i] = 0.0f;
      }

      for (int ki = 0; ki < nk_slice; ki++) {
        int kg = ki_base + ki;
        float sfa = (mi < M) ? __ldg(sa + mi * nk + kg) : 0.0f;
        // BN=128 == one 128-N block, so a single sfb covers all NSUB sub-tiles.
        float sfb0 = __ldg(sb + (on / 128) * nk + kg);
        float sf0 = sfa * sfb0;

        for (int sub = 0; sub < NSUB; sub++, gs++) {
          int ai = gs % NE;
          int ap = (gs / NE) & 1;
          mb_wait_lt(btf + ai * 8, ap); // scratch ai ready
          asm volatile("tcgen05.fence::after_thread_sync;");
          uint32_t ta_ = taddr + ((ew * 32) << 16) + ai * MMA_N;
          float v[16];
          asm volatile(
              "tcgen05.ld.sync.aligned.32x32b.x16.b32 "
              "{%0,%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15}, [%16];"
              : "=f"(v[0]), "=f"(v[1]), "=f"(v[2]), "=f"(v[3]), "=f"(v[4]),
                "=f"(v[5]), "=f"(v[6]), "=f"(v[7]), "=f"(v[8]), "=f"(v[9]),
                "=f"(v[10]), "=f"(v[11]), "=f"(v[12]), "=f"(v[13]), "=f"(v[14]),
                "=f"(v[15])
              : "r"(ta_));
          asm volatile("tcgen05.wait::ld.sync.aligned;");
#pragma unroll
          for (int j = 0; j < 16; j++) {
            acc[sub * MMA_N + j] += v[j] * sf0;
          }
          asm volatile("tcgen05.fence::before_thread_sync;");
          mb_arrive_lt(bte + ai * 8);
        }
      }

      // R2S: stage this CTA's dequantized partial row `et` into the bf16 SMEM
      // tile. Out-of-range rows (mi>=M) carry acc=0 (sfa was 0).
      int crow = c_smem + et * BN * 2;
#pragma unroll
      for (int n = 0; n < BN; n += 2) {
        nv_bfloat162 b = __floats2bfloat162_rn(acc[n], acc[n + 1]);
        uint32_t r = *reinterpret_cast<uint32_t *>(&b);
        asm volatile("st.shared.b32 [%0], %1;" ::"r"(crow + n * 2), "r"(r));
      }

      // S2G epilogue write. OPT #1 STORE/REDUCE-ADD FORK (gflag != nullptr):
      //   k_slice==0 CTA  -> plain tma_store (OVERWRITE the base, no pre-zero),
      //                      then publish gflag[tile]=epoch (release).
      //   k_slice>0  CTA  -> spin until gflag[tile]>=epoch (acquire) so the k0
      //                      base has landed, then tma_reduce_add on top.
      // This removes the host pre-zero (= the in-MPK tensor_init task) entirely.
      // Fallback (gflag == nullptr, Mirage ABI): pure reduce-add into a buffer
      // the caller pre-zeroed (MPK tensor_init), matching the old behavior.
      tma_store_fence_lt();
      asm volatile("bar.sync 13, 128;");
      if (wid == 4 && elect_one_sync_lt()) {
        if (gflag == nullptr) {
          tma_reduce_add_2d(tc_ptr, c_smem, on, om);
          tma_commit_lt();
          tma_wait_lt();
        } else {
          int const tile = bm * nn + bn; // output tile id (ks-independent)
          if (ks == 0) {
            tma_store_2d(tc_ptr, c_smem, on, om); // overwrite base
            tma_commit_lt();
            tma_wait_lt();
            // k0 base is now in GMEM; release-publish so k>0 adds order after it
            asm volatile("fence.acq_rel.gpu;" ::: "memory");
            asm volatile("st.global.release.gpu.b32 [%0], %1;" ::"l"(gflag + tile),
                         "r"(epoch)
                         : "memory");
          } else {
            int got;
            do {
              asm volatile("ld.global.acquire.gpu.b32 %0, [%1];"
                           : "=r"(got)
                           : "l"(gflag + tile)
                           : "memory");
            } while (got < epoch);
            tma_reduce_add_2d(tc_ptr, c_smem, on, om);
            tma_commit_lt();
            tma_wait_lt();
          }
        }
      }
      asm volatile("bar.sync 13, 128;");
    }
  }

  __syncthreads();
  asm volatile("membar.gl;" ::: "memory");
  // SAME-WARP: warp 0 issues the dealloc (matching the alloc above).
  if (wid == 0) {
    asm volatile(
        "tcgen05.dealloc.cta_group::1.sync.aligned.b32 %0, %1;" ::"r"(taddr),
        "r"(TCA));
  }
#endif
}

// ---------------------------------------------------------------------------
// Public task_impl — Mirage 11-param ABI (byte-identical to ws2 reference
// and task.yaml ABI spec). Passes gflag=nullptr so the MPK pre-zero
// (tensor_init) path is used — the TMA reduce-add accumulates partials into
// the scheduler-zeroed output buffer.
// ---------------------------------------------------------------------------
template <int BN, int NS, int NE, int SPLIT_K>
__device__ __noinline__ void fp8_gemm_dense_splitk_tma_reduce_sm100_task_impl(
    CUtensorMap const *ta_ptr,
    CUtensorMap const *tb_ptr,
    float const *__restrict__ sa,
    float const *__restrict__ sb,
    __nv_bfloat16 *__restrict__ C,
    int const M,
    int const N,
    int const K,
    int const worker_idx,
    int const num_workers,
    CUtensorMap const *tc_ptr) {
  task_impl_low_tmem_tpl<BN, NS, NE, SPLIT_K>(
      ta_ptr, tb_ptr, sa, sb, C, M, N, K, worker_idx, num_workers, tc_ptr,
      /*gflag=*/nullptr, /*epoch=*/0);
}

} // namespace fp8_gemm_dense_splitk_low_tmem
// MPK integration: task_register.cc emits
// kernel::fp8_gemm_dense_splitk_tma_reduce::fp8_gemm_dense_splitk_tma_reduce_sm100_task_impl<>().
// The ferret-produced header defines everything in fp8_gemm_dense_splitk_low_tmem;
// alias it so the existing emitter resolves without a .cc edit (rebuild-free).
namespace fp8_gemm_dense_splitk_tma_reduce = fp8_gemm_dense_splitk_low_tmem;
} // namespace kernel
