// Generated by ferret kernel-extractor on 2026-06-05 from kernel.cu
// of workspace tag v002. Source workspace: /home/muhengl/ferret/workspace1.
// Mirage target task header:
//   /home/muhengl/mirage/include/mirage/persistent_kernel/tasks/blackwell/
//     fp8_gemm_dense_mediumm_sm100.cuh  (direct structural mirror)
// SOTA beaten: vLLM/cuBLASLt FP8 e4m3 at 169.8% / 128.5% / 161.4% / 177.9%
//   (qkv_a_BN32, o_proj_BN32, qkv_a_BN16, gate_up_BN32; all target 115%).
//
// WHAT THIS IS: the "fine-N" FP8 GEMM decode variant. The device function body
// IS the in-tree mediumm body (fp8_gemm_dense_common::task_impl_tpl<BN,NS,4>),
// unchanged. The ONLY delta vs the in-tree TASK_FP8_GEMM_DENSE_MEDIUMM_SM100 is
// host-side: the B TMA descriptor must use box_outer=BN (not 128) to match the
// per-slot SMEM footprint SB=BN*BK. That is a tma.cuh concern (OUTER_BOX param
// at lines 1607-1651 of the Mirage tma.cuh), NOT part of this device header.
//
// Per-config locked (BN, NS) for delivery (NE=4 baked):
//   qkv_a_BN32  (K=7168, N=2176): BN=32, NS=8
//   o_proj_BN32 (K=1792, N=7168): BN=64, NS=4
//   qkv_a_BN16  (K=7168, N=2176): BN=16, NS=8
//   gate_up_BN32 (K=7168, N=1024): BN=32, NS=8
//
// Crash-safety: single-CTA-per-output-tile, direct bf16 store, NO split-K /
// reduce, NO red.global.add. cta_group::1 only.
// NOTE: alloc on warp2 / dealloc on warp0 = cross-warp (inherited from
// mediumm). Mediumm has survived TP=2 co-residency in practice (single-CTA-
// per-tile); a TP=2 co-resident-MLA smoke is still required before landing.
//
// LANDING FLAG for Mirage main agent:
//   tma.cuh TASK_FP8_GEMM_DENSE_MEDIUMM_SM100 case hardcodes OUTER_BOX=128
//   for the B descriptor (param_id==1). Fine-N requires a BN-parameterized
//   branch there. A new TASK_FP8_GEMM_DENSE_FINEN_SM100 task-type enum +
//   tma.cuh case is the clean path.

#pragma once

#include "fp8_gemm_dense_sm100_common.cuh"

namespace kernel {
namespace fp8_gemm_dense_finen {

// Main task function — fine-N variant of the dense FP8 GEMM decode kernel.
// Signature mirrors fp8_gemm_dense_mediumm_sm100_task_impl exactly; the only
// semantic difference is that the Mirage tma.cuh dispatcher must build the B
// TMA descriptor with OUTER_BOX=BN instead of 128.
//
// Parameters:
//   ta_ptr      : A FP8 e4m3 [M, K] row-major TMA desc, box_outer=128 (BM)
//   tb_ptr      : B FP8 e4m3 [N, K] row-major TMA desc, box_outer=BN  **
//   sa          : activation scale [M, K/128] row-major float32
//   sb          : weight scale [N/128, K/128] row-major float32
//   C           : output [M, N] bf16 row-major
//   M, N, K     : matrix dimensions
//   worker_idx  : this CTA's persistent-kernel worker index (= blockIdx.x)
//   num_workers : total workers in the launch (= gridDim.x)
//
// ** The B descriptor box_outer=BN is the sole tma.cuh requirement for landing.
template <int BN, int NS>
__device__ __noinline__ void
    fp8_gemm_dense_finen_sm100_task_impl(CUtensorMap const *ta_ptr,
                                         CUtensorMap const *tb_ptr,
                                         float const *__restrict__ sa,
                                         float const *__restrict__ sb,
                                         __nv_bfloat16 *__restrict__ C,
                                         int const M,
                                         int const N,
                                         int const K,
                                         int const worker_idx,
                                         int const num_workers,
                                         int const C_row_stride = -1) {
  fp8_gemm_dense_common::task_impl_tpl<BN, NS, /*NE=*/4>(ta_ptr,
                                                         tb_ptr,
                                                         sa,
                                                         sb,
                                                         C,
                                                         M,
                                                         N,
                                                         K,
                                                         worker_idx,
                                                         num_workers,
                                                         C_row_stride);
}

// Shared-memory size helper — matches mediumm formula exactly.
// Formula: NS*(BM*BK + BN*BK) + (NS*2+NE*2)*8 + 8 + 1024
//   with BM=128, BK=128, NE=4.
template <int BN, int NS>
__host__ __device__ inline constexpr int fp8_gemm_dense_finen_smem_size() {
  return fp8_gemm_dense_common::smem_size_tpl<BN, NS, /*NE=*/4>();
}

} // namespace fp8_gemm_dense_finen
} // namespace kernel
