// Generated by ferret kernel-extractor on 2026-06-19 from kernel.cu
// of workspace tag v006. Source workspace: /home/muhengl/ferret/workspace8.
// Mirage target task header:
//   /home/muhengl/mirage/include/mirage/persistent_kernel/tasks/blackwell/mla_mtp_decode_tp8_sm100.cuh
// SOTA beaten (standalone vs real in-tree baseline): KV128=1.53x KV256=1.55x
//   KV512=1.51x KV4096=1.51x (best-effort; in-MPK co-residency target
//   infeasible standalone — see workspace8/progress.md ## Ceiling).
//
// KEY DIFFERENCES vs the in-tree v7 header (2026-06-18):
//   - TILE_S = 32 (fine-split; v7 bakes TILE_S=128)
//   - NUM_QK_STAGES = 5, MAX_STAGES = 5 (v7 uses 3 to make room for o_save
//   smem)
//   - o_save is a register array float[1 or TILE_S], NOT smem (SINGLE_TILE=true
//     → array is float[1], dead code; no OSAVE_SMEM_BYTES)
//   - SMEM_SIZE = NUM_QK_STAGES*2*TILE_BYTES = 5*2*16384 = 163840 B (~160 KB)
//   - PV contraction uses K_MMA = TILE_S/MMA_K (= 2 for TILE_S=32; v7 bakes
//   K_MMA=8)
//   - SINGLE-PASS SOFTMAX (v006): load all TILE_S score columns into float
//   scores[]
//     register array ONCE (Pass A, 2 tcgen05.ld at TILE_S=32), then Pass B is
//     REGISTER-ONLY (no second TMEM sweep):
//     exp2(scores[]-tile_max)+sum+P-write. Softmax TMEM reads reduced from 4
//     sweeps to 2 (saves 2 full TMEM sweeps per tile). (v004 two-pass used 4
//     sweeps: pass1 max + pass2 exp2+P.)
//   - pass2 softmax sweeps only c < TILE_S columns (v003 correctness fix)
//   - epilogue issues 4 tcgen05.ld per V-chunk before one wait (v004 batching)
//   - page_indices / first_page_pos used for paged KV (kv_row computed per
//   tile)
//   - WRITE_FINAL template param: when true, epilogue writes final O[bi,q,h,d]
//     directly (skips partial-O layout); when false (normal MPK path), writes
//     Oa[block_linear, d, row] + La[block_linear, row].
//
// ABI reconciliation notes for Mirage main agent:
//   1. Drop-in for mla_mtp_decode_tp8_sm100.cuh ONLY if the caller sets
//      TILE_S=32 TMA boxes (bd={64,32,1}) for the KV tensor map. The Q box
//      is unchanged (bd={64,hpb,1}).
//   2. cudaFuncSetAttribute for MaxDynamicSharedMemorySize must be raised
//      to SMEM_SIZE = 163840 (was 164864 for v7; slightly smaller here since
//      no o_save smem slab).
//   3. At TILE_S=32, sk = ceil(KV/32); ALL configs give tps=1 →
//      SINGLE_TILE=true is always the right dispatch. SINGLE_TILE=false
//      branch is dead but compiled-in (harmless; 0 runtime overhead at tps=1).
//   4. KV4096: the standalone harness falls back to TILE_S=128 for KV=4096
//      (TILE_S=32 over-splits at 128 CTAs → 1.00× vs 0.96×). In-MPK, the
//      caller must decide per-config dispatch. This header bakes TILE_S=32
//      throughout; a separate TILE_S=128 instantiation is the in-tree v7.
//   5. MPK_DSV3_FORCEINLINE: same macro convention as v7; define to
//      __forceinline__ for -rdc=true build to avoid caller-save spill.

#pragma once
#include <cuda.h>
#include <cudaTypedefs.h>
#include <cuda_bf16.h>

// MPK_DSV3_FORCEINLINE (default-OFF, byte-identical default build):
// When set, mla_mtp_tp8_main is forceinlined into execute_worker (via
// _execute_task -> execute_task_noinline) to avoid caller-save spill under
// -rdc=true. Same pattern as fp8_gemm_dense_finen_sm100.cuh.
#ifndef MPK_DSV3_TASK_INLINE
#ifdef MPK_DSV3_FORCEINLINE
#define MPK_DSV3_TASK_INLINE __forceinline__
#else
#define MPK_DSV3_TASK_INLINE __noinline__
#endif
#endif

namespace kernel {
namespace mla_mtp_tp8 {

// See mla_mtp_decode_tp2_sm100.cuh for rationale. ID 12 = CUTLASS user
// range; IDs 1..7 are reserved (bugfix.md Bug 19).
#define MLA_TP_SYNC_ACTIVE() asm volatile("bar.sync 12, 128;" ::: "memory")

static constexpr int NUM_HEADS = 16;
static constexpr int D_K = 576;
static constexpr int D_V = 512;
// Fine-split tile: 32 tokens/tile (vs in-tree v7's 128). Gives 4x more
// split-CTAs at short KV (KV512 → 16 CTAs vs 4) → 1.51-1.55x speedup
// over the real in-tree baseline.
static constexpr int TILE_S = 32;
static constexpr int BK = 64; // 128B swizzle tile width
static constexpr int MMA_K = 16;
static constexpr int K_ITERS = D_K / BK;  // 9 for QK
static constexpr int V_CHUNKS = D_V / BK; // 8
static constexpr int TB = 128;

// Pipeline stages — kept at 5 (v7 reduced to 3 to free smem for o_save slab;
// here o_save stays in registers so we can keep 5-stage QK prefetch depth).
static constexpr int NUM_QK_STAGES = 5;
static constexpr int NUM_PV_STAGES = 3;
static constexpr int MAX_STAGES = 5;

// SMEM tile: 128 rows x BK cols x 2 bytes = 16384 B
// (slot stays 128-row for swizzle/descriptor stride validity; TMA writes
//  only TILE_S=32 rows per fill; expect_tx = TILE_S*BK*2, not TILE_BYTES)
static constexpr int TILE_BYTES = 128 * BK * 2;

// Total smem: QK pipeline stages only (no o_save slab; o_save is register).
// = 5*2*16384 = 163840 B (~160 KB). B200 budget: 205 KB dynamic. PASS.
static constexpr int SMEM_SIZE = NUM_QK_STAGES * 2 * TILE_BYTES;

// Bytes actually transferred per K/V TMA fill = TILE_S rows × BK cols × 2B.
// Must match expect_tx. The slot is TILE_BYTES (128-row) for swizzle validity.
static constexpr int KV_TX_BYTES = TILE_S * BK * 2;

// Reduce kernel thread-block geometry
static constexpr int RD_DV = 2;
static constexpr int RD_TB = 256;

// ============ PTX Helpers ============
namespace ptx {

__device__ __forceinline__ uint32_t elect_sync() {
  uint32_t p = 0;
  asm volatile("{\n\t.reg .pred %%px;\n\t"
               "elect.sync _|%%px, 0xFFFFFFFF;\n\t"
               "@%%px mov.s32 %0, 1;\n\t}"
               : "+r"(p));
  return p;
}

__device__ __forceinline__ void mbar_init(int addr, int count) {
  asm volatile("mbarrier.init.shared::cta.b64 [%0], %1;" ::"r"(addr),
               "r"(count));
}

__device__ __forceinline__ void mbar_wait(int addr, int phase) {
  asm volatile("{\n\t.reg .pred P;\n\t"
               "WAIT: mbarrier.try_wait.parity.acquire.cta.shared::cta.b64 P, "
               "[%0], %1, 0x989680;\n\t"
               "@P bra DONE;\n\t"
               "bra WAIT;\n\t"
               "DONE:\n\t}" ::"r"(addr),
               "r"(phase));
}

__device__ __forceinline__ void mbar_tx(int addr, int bytes) {
  asm volatile(
      "mbarrier.arrive.expect_tx.release.cta.shared::cta.b64 _, [%0], %1;" ::
          "r"(addr),
      "r"(bytes)
      : "memory");
}

__device__ __forceinline__ constexpr uint64_t desc_enc(uint64_t x) {
  return (x & 0x3FFFFULL) >> 4;
}

__device__ __forceinline__ uint64_t make_desc(int smem_addr) {
  constexpr uint64_t SBO = 8ULL * 128;
  return desc_enc(smem_addr) | (desc_enc(SBO) << 32) | (1ULL << 46) |
         (2ULL << 61);
}

__device__ __forceinline__ void tcgen05_mma(
    int taddr, uint64_t a_desc, uint64_t b_desc, uint32_t idesc, int acc) {
  asm volatile(
      "{\n\t.reg .pred p;\n\t"
      "setp.ne.b32 p, %4, 0;\n\t"
      "tcgen05.mma.cta_group::1.kind::f16 [%0], %1, %2, %3, p;\n\t}" ::"r"(
          taddr),
      "l"(a_desc),
      "l"(b_desc),
      "r"(idesc),
      "r"(acc));
}

__device__ __forceinline__ void tcgen05_commit(int mbar_addr) {
  asm volatile("tcgen05.commit.cta_group::1.mbarrier::arrive::one.shared::"
               "cluster.b64 [%0];" ::"r"(mbar_addr)
               : "memory");
}

} // namespace ptx

// ============ Main MLA Kernel ============
// TILE_S=32 fine-split variant with single-pass online softmax (v006).
// Template parameters:
//   SINGLE_TILE: true when tps=1 (every config at TILE_S=32 meets this;
//     false branch is dead but harmless — compiled-in for ABI compatibility).
//   WRITE_FINAL: true → epilogue writes O[bi, q, h, d] directly (sk=1 fast
//     path); false → writes partial-O + LSE for reduce.
template <bool SINGLE_TILE, bool WRITE_FINAL>
__device__ MPK_DSV3_TASK_INLINE void mla_mtp_tp8_main(
    CUtensorMap const *__restrict__ Q_tm_ptr,
    CUtensorMap const *__restrict__ KV_tm_ptr,
    nv_bfloat16 *__restrict__ Oa,
    float *__restrict__ La,
    float ss,
    int kv_len,
    int sk,
    int Q_LEN,
    int qpg,
    int const *__restrict__ page_indices,
    int first_page_pos,
    int Q_LEN_real, // unpadded real decode length (Q_LEN is padded to even)
    int block_x,
    int block_y) {
  if (threadIdx.x >= TB) {
    return;
  }
  // Dual-dispatch gate: TP=8 handles Q_LEN_real <= 8.
  // Longer sequences are routed to a different kernel.
  if (Q_LEN_real > 8) {
    return;
  }
  int const tid = threadIdx.x;
  int const wid = tid / 32;

  int const gi = block_x / sk;
  int const si = block_x % sk;
  int const bi = block_y;

  int const num_groups = Q_LEN / qpg; // Q_LEN is padded to multiple of qpg
  if (gi >= num_groups) {
    return;
  }

  int const kvt = (kv_len + TILE_S - 1) / TILE_S;
  int const tps = (kvt + sk - 1) / sk;
  int const t0 = si * tps;
  int const t1 = min(t0 + tps, kvt);
  if (t0 >= t1) {
    // Empty split: write sentinel LSE so reduce ignores this slot.
    int block_linear = bi * num_groups * sk + gi * sk + si;
    if (tid < 128) {
      La[block_linear * 128 + tid] = -1e30f;
    }
    return;
  }

  int const hpb = NUM_HEADS;
  int const actual_qpg = min(qpg, Q_LEN - gi * qpg);

  // ===== SMEM layout =====
  // Each QK stage: [Q_tile(TILE_BYTES)] [K_tile(TILE_BYTES)]
  // PV reuses the same area (stages 0..NUM_PV_STAGES-1).
  extern __shared__ __align__(1024) char smem_buf[];
  int const work_smem = __cvta_generic_to_shared(smem_buf);

  __shared__ uint64_t mbar_buf[12];
  __shared__ int tmem_addr_buf[1];
  int const tma_bar = __cvta_generic_to_shared(&mbar_buf[0]);
  int const mma_bar = __cvta_generic_to_shared(&mbar_buf[MAX_STAGES]);
  int const mainloop_bar = __cvta_generic_to_shared(&mbar_buf[2 * MAX_STAGES]);

  // Init barriers + alloc TMEM. Both alloc AND dealloc from warp 0
  // (same-warp CuTe permit invariant; cross-warp alloc drifts under
  // Independent Thread Scheduling at multi-rank co-residency → IMA).
  if (wid == 0) {
    if (ptx::elect_sync()) {
      for (int i = 0; i < MAX_STAGES; i++) {
        ptx::mbar_init(tma_bar + i * 8, 1);
        ptx::mbar_init(mma_bar + i * 8, 1);
      }
      ptx::mbar_init(mainloop_bar, 1);
      asm volatile("fence.mbarrier_init.release.cluster;");
    }
    int addr_smem = __cvta_generic_to_shared(tmem_addr_buf);
    asm volatile(
        "tcgen05.alloc.cta_group::1.sync.aligned.shared::cta.b32 [%0], %1;" ::
            "r"(addr_smem),
        "r"(D_V));
  }
  MLA_TP_SYNC_ACTIVE();
  int const taddr = tmem_addr_buf[0];

  int const hpb_bytes = hpb * BK * 2;

  // QK instruction descriptor: N = TILE_S >> 3 = 4 (at TILE_S=32).
  // (v7 bakes TILE_S=128 → N=16; this header bakes TILE_S=32 → N=4.)
  constexpr uint32_t idesc_qk = (1U << 4) | (1U << 7) | (1U << 10) |
                                ((uint32_t)(TILE_S >> 3) << 17) |
                                ((uint32_t)(128 >> 4) << 24);

  constexpr uint32_t idesc_pv = (1U << 4) | (1U << 7) | (1U << 10) |
                                (1U << 16) | ((uint32_t)(BK >> 3) << 17) |
                                ((uint32_t)(128 >> 4) << 24);

  // PV contraction: K_MMA = TILE_S / MMA_K = 32/16 = 2 (vs 8 in v7).
  // Only 2 MMAs per V-chunk; P[c>=32] is zero and never loaded (v003 fix).
  constexpr int K_MMA = TILE_S / MMA_K;
  constexpr int MMA_PER_BLK = BK / MMA_K; // = 4

  int block_linear = bi * num_groups * sk + gi * sk + si;
  nv_bfloat16 *Oout = Oa + block_linear * D_V * 128;
  float row_max = -1e30f;
  float row_sum = 0.0f;

  // Register buffer for partial-O (multi-tile accumulation).
  // At SINGLE_TILE=true this is a 1-element placeholder; at false it holds
  // TILE_S=32 floats per thread (128 bytes per thread).
  float o_save[SINGLE_TILE ? 1 : TILE_S];

  // ===== Main loop over KV tiles =====
  for (int tile = t0; tile < t1; tile++) {
    int const kvs = tile * TILE_S;
    int const tlen = min(TILE_S, kv_len - kvs);

    // Paged KV: kv_row is the first row index of this tile in global KV.
    int const kv_row = (page_indices == nullptr)
                           ? bi * kv_len + kvs
                           : page_indices[first_page_pos + tile] * TILE_S;

    // Save O[0..TILE_S-1] from TMEM into register buffer (multi-tile only).
    if (!SINGLE_TILE && tile > t0) {
      for (int c = 0; c < TILE_S; c += 16) {
        int addr = taddr + (tid << 16) + c;
        asm volatile(
            "tcgen05.ld.sync.aligned.32x32b.x16.b32 "
            "{%0,%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15}, [%16];"
            : "=f"(o_save[c + 0]),
              "=f"(o_save[c + 1]),
              "=f"(o_save[c + 2]),
              "=f"(o_save[c + 3]),
              "=f"(o_save[c + 4]),
              "=f"(o_save[c + 5]),
              "=f"(o_save[c + 6]),
              "=f"(o_save[c + 7]),
              "=f"(o_save[c + 8]),
              "=f"(o_save[c + 9]),
              "=f"(o_save[c + 10]),
              "=f"(o_save[c + 11]),
              "=f"(o_save[c + 12]),
              "=f"(o_save[c + 13]),
              "=f"(o_save[c + 14]),
              "=f"(o_save[c + 15])
            : "r"(addr));
        asm volatile("tcgen05.wait::ld.sync.aligned;");
      }
    }

    // ===== QK Phase: co-load Q + K, then run QK MMA =====
    MLA_TP_SYNC_ACTIVE();
    if (wid == 0 && ptx::elect_sync()) {
      for (int i = 0; i < NUM_QK_STAGES; i++) {
        ptx::mbar_init(tma_bar + i * 8, 1);
        ptx::mbar_init(mma_bar + i * 8, 1);
      }
      ptx::mbar_init(mainloop_bar, 1);
      asm volatile("fence.mbarrier_init.release.cluster;");
    }
    MLA_TP_SYNC_ACTIVE();

    if (wid == 0 && ptx::elect_sync()) {
      // TMA producer: co-load Q[ki] + K[ki] per pipeline stage.
      int phase = 0;
      for (int ki = 0; ki < K_ITERS; ki++) {
        int stage = ki % NUM_QK_STAGES;
        ptx::mbar_wait(mma_bar + stage * 8, phase ^ 1);
        if (stage == NUM_QK_STAGES - 1) {
          phase ^= 1;
        }

        int q_stage = work_smem + stage * 2 * TILE_BYTES;
        int k_stage = q_stage + TILE_BYTES;

        // expect_tx = KV_TX_BYTES (TILE_S rows, not TILE_BYTES=128 rows)
        ptx::mbar_tx(tma_bar + stage * 8, KV_TX_BYTES + hpb_bytes * actual_qpg);
        // Load K[ki] for this tile
        asm volatile("cp.async.bulk.tensor.3d.shared::cta.global.mbarrier::"
                     "complete_tx::bytes "
                     "[%0], [%1, {%2, %3, %4}], [%5];" ::"r"(k_stage),
                     "l"(KV_tm_ptr),
                     "r"(0),
                     "r"(kv_row),
                     "r"(ki),
                     "r"(tma_bar + stage * 8)
                     : "memory");
        // Load Q[ki] for each query in the group
        for (int q = 0; q < actual_qpg; q++) {
          int actual_q_idx = gi * qpg + q;
          int global_row = bi * Q_LEN * NUM_HEADS + actual_q_idx * NUM_HEADS;
          asm volatile(
              "cp.async.bulk.tensor.3d.shared::cta.global.mbarrier::"
              "complete_tx::bytes "
              "[%0], [%1, {%2, %3, %4}], [%5];" ::"r"(q_stage + q * hpb_bytes),
              "l"(Q_tm_ptr),
              "r"(0),
              "r"(global_row),
              "r"(ki),
              "r"(tma_bar + stage * 8)
              : "memory");
        }
      }
    } else if (wid == 1 && ptx::elect_sync()) {
      // MMA consumer: wait for each stage then run QK MMA.
      int phase = 0;
      for (int ki = 0; ki < K_ITERS; ki++) {
        int stage = ki % NUM_QK_STAGES;
        ptx::mbar_wait(tma_bar + stage * 8, phase);
        asm volatile("tcgen05.fence::after_thread_sync;");
        if (stage == NUM_QK_STAGES - 1) {
          phase ^= 1;
        }

        int q_stage = work_smem + stage * 2 * TILE_BYTES;
        int k_stage = q_stage + TILE_BYTES;

        for (int k2 = 0; k2 < BK / MMA_K; k2++) {
          uint64_t a_desc = ptx::make_desc(q_stage + k2 * 32);
          uint64_t b_desc = ptx::make_desc(k_stage + k2 * 32);
          ptx::tcgen05_mma(
              taddr, a_desc, b_desc, idesc_qk, (ki == 0 && k2 == 0) ? 0 : 1);
        }
        ptx::tcgen05_commit(mma_bar + stage * 8);
      }
      ptx::tcgen05_commit(mainloop_bar);
    }

    MLA_TP_SYNC_ACTIVE();
    ptx::mbar_wait(mainloop_bar, 0);

    // ===== Single-Pass Online Softmax (v006) =====
    // Pass A (TMEM→regs): load all TILE_S score columns ONCE into the
    // float scores[] register array while tracking tile_max. At TILE_S=32
    // this is 2 tcgen05.ld (was 2 in the old pass1 as well; the savings
    // come from eliminating pass2's 2 extra TMEM sweeps entirely).
    // Pass B (register-only): exp2(scores[]-tile_max) + sum + P-write.
    // Total TMEM softmax reads: 2 (was 4 in v004 two-pass).
    asm volatile("tcgen05.fence::after_thread_sync;");

    // Reinit PV barriers and preload first NUM_PV_STAGES V chunks
    // during softmax to overlap TMA with softmax compute.
    if (wid == 0 && ptx::elect_sync()) {
      for (int i = 0; i < NUM_PV_STAGES; i++) {
        ptx::mbar_init(tma_bar + i * 8, 1);
        ptx::mbar_init(mma_bar + i * 8, 1);
      }
      ptx::mbar_init(mainloop_bar, 1);
      asm volatile("fence.mbarrier_init.release.cluster;");
      int V_buf_base_pre = work_smem + 2 * TILE_BYTES;
      for (int vc = 0; vc < min(NUM_PV_STAGES, V_CHUNKS); vc++) {
        int v_smem = V_buf_base_pre + vc * TILE_BYTES;
        ptx::mbar_tx(tma_bar + vc * 8, KV_TX_BYTES);
        asm volatile("cp.async.bulk.tensor.3d.shared::cta.global.mbarrier::"
                     "complete_tx::bytes "
                     "[%0], [%1, {%2, %3, %4}], [%5];" ::"r"(v_smem),
                     "l"(KV_tm_ptr),
                     "r"(0),
                     "r"(kv_row),
                     "r"(vc),
                     "r"(tma_bar + vc * 8)
                     : "memory");
      }
    }

    // Per-thread causal limit computation.
    int q_in_group = tid / hpb;
    int actual_q_tid = gi * qpg + q_in_group;
    int effective_len;
    if (actual_q_tid < Q_LEN_real) {
      int causal_limit = kv_len;
      if (Q_LEN_real > 1) {
        causal_limit = kv_len - Q_LEN_real + actual_q_tid + 1;
      }
      effective_len = min(tlen, causal_limit - kvs);
      if (effective_len < 0) {
        effective_len = 0;
      }
    } else {
      effective_len = 0;
    }

    // Pass A: load all TILE_S QK score columns from TMEM into registers,
    // scaling by ss*log2(e) and masking, while tracking tile_max.
    float const ss_log2e = ss * 1.4426950408889634f;
    float scores[TILE_S];
    float tile_max = -1e30f;
    for (int c = 0; c < TILE_S; c += 16) {
      float t16[16];
      int addr = taddr + (tid << 16) + c;
      asm volatile(
          "tcgen05.ld.sync.aligned.32x32b.x16.b32 "
          "{%0,%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15}, [%16];"
          : "=f"(t16[0]),
            "=f"(t16[1]),
            "=f"(t16[2]),
            "=f"(t16[3]),
            "=f"(t16[4]),
            "=f"(t16[5]),
            "=f"(t16[6]),
            "=f"(t16[7]),
            "=f"(t16[8]),
            "=f"(t16[9]),
            "=f"(t16[10]),
            "=f"(t16[11]),
            "=f"(t16[12]),
            "=f"(t16[13]),
            "=f"(t16[14]),
            "=f"(t16[15])
          : "r"(addr));
      asm volatile("tcgen05.wait::ld.sync.aligned;");
#pragma unroll
      for (int i = 0; i < 16; i++) {
        float v = (c + i < effective_len) ? t16[i] * ss_log2e : -1e30f;
        scores[c + i] = v;
        tile_max = fmaxf(tile_max, v);
      }
    }

    // Pass B (register-only): exp2(scores[]-tile_max) + sum + write P to SMEM.
    // No TMEM reads in this pass — scores[] array already in registers.
    int P0_smem = work_smem;
    int P1_smem = work_smem + TILE_BYTES;
    float tile_sum = 0.0f;

    for (int c = 0; c < TILE_S; c += 16) {
      int half = c >> 6;
      int p_base = (half == 0) ? P0_smem : P1_smem;
      int row_base = p_base + tid * 128;
      {
        float t16[16];
#pragma unroll
        for (int i = 0; i < 16; i++) {
          float e =
              (c + i < effective_len) ? exp2f(scores[c + i] - tile_max) : 0.0f;
          t16[i] = e;
          tile_sum += e;
        }

        // Pack and write 16 bf16 values to P smem (swizzled layout).
        int g_start = (c % 64);
#pragma unroll
        for (int gg = 0; gg < 16; gg += 8) {
          int g = g_start + gg;
          uint32_t w0, w1, w2, w3;
          {
            nv_bfloat16 b0 = __float2bfloat16(t16[gg + 0]);
            nv_bfloat16 b1 = __float2bfloat16(t16[gg + 1]);
            w0 = (uint32_t)(*(uint16_t *)&b0) |
                 ((uint32_t)(*(uint16_t *)&b1) << 16);
          }
          {
            nv_bfloat16 b0 = __float2bfloat16(t16[gg + 2]);
            nv_bfloat16 b1 = __float2bfloat16(t16[gg + 3]);
            w1 = (uint32_t)(*(uint16_t *)&b0) |
                 ((uint32_t)(*(uint16_t *)&b1) << 16);
          }
          {
            nv_bfloat16 b0 = __float2bfloat16(t16[gg + 4]);
            nv_bfloat16 b1 = __float2bfloat16(t16[gg + 5]);
            w2 = (uint32_t)(*(uint16_t *)&b0) |
                 ((uint32_t)(*(uint16_t *)&b1) << 16);
          }
          {
            nv_bfloat16 b0 = __float2bfloat16(t16[gg + 6]);
            nv_bfloat16 b1 = __float2bfloat16(t16[gg + 7]);
            w3 = (uint32_t)(*(uint16_t *)&b0) |
                 ((uint32_t)(*(uint16_t *)&b1) << 16);
          }
          int byte_off = g * 2;
          int swizzled =
              (byte_off & ~0xF) ^ ((tid & 7) << 4) | (byte_off & 0xF);
          int saddr = row_base + swizzled;
          asm volatile("st.shared.v4.b32 [%0], {%1,%2,%3,%4};" ::"r"(saddr),
                       "r"(w0),
                       "r"(w1),
                       "r"(w2),
                       "r"(w3));
        }
      }
    }

    float nm = fmaxf(row_max, tile_max);
    float corr = exp2f(row_max - nm);
    float ts = tile_sum * exp2f(tile_max - nm);

    // Scale O[TILE_S..D_V-1] in TMEM for multi-tile correction.
    if (!SINGLE_TILE && tile > t0) {
      MLA_TP_SYNC_ACTIVE();
      for (int c = TILE_S; c < D_V; c += 16) {
        float t16[16];
        int addr = taddr + (tid << 16) + c;
        asm volatile(
            "tcgen05.ld.sync.aligned.32x32b.x16.b32 "
            "{%0,%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15}, [%16];"
            : "=f"(t16[0]),
              "=f"(t16[1]),
              "=f"(t16[2]),
              "=f"(t16[3]),
              "=f"(t16[4]),
              "=f"(t16[5]),
              "=f"(t16[6]),
              "=f"(t16[7]),
              "=f"(t16[8]),
              "=f"(t16[9]),
              "=f"(t16[10]),
              "=f"(t16[11]),
              "=f"(t16[12]),
              "=f"(t16[13]),
              "=f"(t16[14]),
              "=f"(t16[15])
            : "r"(addr));
        asm volatile("tcgen05.wait::ld.sync.aligned;");
#pragma unroll
        for (int i = 0; i < 16; i++) {
          t16[i] *= corr;
        }
        uint32_t *u = (uint32_t *)t16;
        asm volatile(
            "tcgen05.st.sync.aligned.32x32b.x16.b32 [%0], "
            "{%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15,%16};" ::"r"(
                addr),
            "r"(u[0]),
            "r"(u[1]),
            "r"(u[2]),
            "r"(u[3]),
            "r"(u[4]),
            "r"(u[5]),
            "r"(u[6]),
            "r"(u[7]),
            "r"(u[8]),
            "r"(u[9]),
            "r"(u[10]),
            "r"(u[11]),
            "r"(u[12]),
            "r"(u[13]),
            "r"(u[14]),
            "r"(u[15]));
      }
    }

    row_max = nm;
    row_sum = corr * row_sum + ts;

    // ===== PV Phase =====
    int V_buf_base = work_smem + 2 * TILE_BYTES;
    int pv_acc_base = (!SINGLE_TILE && tile > t0) ? 1 : 0;

    MLA_TP_SYNC_ACTIVE();

    if (wid == 0 && ptx::elect_sync()) {
      // V[0..NUM_PV_STAGES-1] already preloaded during softmax.
      // Continue loading V[NUM_PV_STAGES..V_CHUNKS-1].
      int phase = 0;
      for (int vc = 0; vc < NUM_PV_STAGES; vc++) {
        int stage = vc % NUM_PV_STAGES;
        if (stage == NUM_PV_STAGES - 1) {
          phase ^= 1;
        }
      }
      for (int vc = NUM_PV_STAGES; vc < V_CHUNKS; vc++) {
        int stage = vc % NUM_PV_STAGES;
        ptx::mbar_wait(mma_bar + stage * 8, phase ^ 1);
        if (stage == NUM_PV_STAGES - 1) {
          phase ^= 1;
        }

        int v_smem = V_buf_base + stage * TILE_BYTES;
        ptx::mbar_tx(tma_bar + stage * 8, KV_TX_BYTES);
        asm volatile("cp.async.bulk.tensor.3d.shared::cta.global.mbarrier::"
                     "complete_tx::bytes "
                     "[%0], [%1, {%2, %3, %4}], [%5];" ::"r"(v_smem),
                     "l"(KV_tm_ptr),
                     "r"(0),
                     "r"(kv_row),
                     "r"(vc),
                     "r"(tma_bar + stage * 8)
                     : "memory");
      }
    } else if (wid == 1 && ptx::elect_sync()) {
      int phase = 0;
      for (int vc = 0; vc < V_CHUNKS; vc++) {
        int stage = vc % NUM_PV_STAGES;
        ptx::mbar_wait(tma_bar + stage * 8, phase);
        asm volatile("tcgen05.fence::after_thread_sync;");
        if (stage == NUM_PV_STAGES - 1) {
          phase ^= 1;
        }

        int v_smem = V_buf_base + stage * TILE_BYTES;
        int out_taddr = taddr + vc * BK;

        int vc_acc_base = (vc < 2) ? 0 : pv_acc_base;
        int first_in_vc = 1;
        // Contract exactly TILE_S=32 keys = K_MMA=2 MMAs per V-chunk.
        // (v7 bakes K_MMA=8 for TILE_S=128; this header bakes K_MMA=2.)
        for (int kk = 0; kk < K_MMA; kk++) {
          int k1 = kk / MMA_PER_BLK;
          int kj = kk % MMA_PER_BLK;
          int p_addr = (k1 == 0) ? P0_smem : P1_smem;
          int v_k1_off = k1 * 64 * 128;
          uint64_t a_desc = ptx::make_desc(p_addr + kj * 32);
          uint64_t b_desc = ptx::make_desc(v_smem + v_k1_off + kj * 16 * 128);
          int acc = (first_in_vc && !vc_acc_base) ? 0 : 1;
          ptx::tcgen05_mma(out_taddr, a_desc, b_desc, idesc_pv, acc);
          first_in_vc = 0;
        }
        ptx::tcgen05_commit(mma_bar + stage * 8);
      }
      ptx::tcgen05_commit(mainloop_bar);
    }

    MLA_TP_SYNC_ACTIVE();
    ptx::mbar_wait(mainloop_bar, 0);

    // Merge saved O[0..TILE_S-1] with PV result (multi-tile only).
    asm volatile("tcgen05.fence::after_thread_sync;");
    if (!SINGLE_TILE && tile > t0) {
      for (int c = 0; c < TILE_S; c += 16) {
        float t16[16];
        int addr = taddr + (tid << 16) + c;
        asm volatile(
            "tcgen05.ld.sync.aligned.32x32b.x16.b32 "
            "{%0,%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15}, [%16];"
            : "=f"(t16[0]),
              "=f"(t16[1]),
              "=f"(t16[2]),
              "=f"(t16[3]),
              "=f"(t16[4]),
              "=f"(t16[5]),
              "=f"(t16[6]),
              "=f"(t16[7]),
              "=f"(t16[8]),
              "=f"(t16[9]),
              "=f"(t16[10]),
              "=f"(t16[11]),
              "=f"(t16[12]),
              "=f"(t16[13]),
              "=f"(t16[14]),
              "=f"(t16[15])
            : "r"(addr));
        asm volatile("tcgen05.wait::ld.sync.aligned;");
#pragma unroll
        for (int i = 0; i < 16; i++) {
          t16[i] += corr * o_save[c + i];
        }
        uint32_t *u = (uint32_t *)t16;
        asm volatile(
            "tcgen05.st.sync.aligned.32x32b.x16.b32 [%0], "
            "{%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15,%16};" ::"r"(
                addr),
            "r"(u[0]),
            "r"(u[1]),
            "r"(u[2]),
            "r"(u[3]),
            "r"(u[4]),
            "r"(u[5]),
            "r"(u[6]),
            "r"(u[7]),
            "r"(u[8]),
            "r"(u[9]),
            "r"(u[10]),
            "r"(u[11]),
            "r"(u[12]),
            "r"(u[13]),
            "r"(u[14]),
            "r"(u[15]));
      }
    }
  }

  // ===== Epilogue: read O from TMEM, normalize, store output =====
  asm volatile("tcgen05.fence::after_thread_sync;");
  int const valid_rows = actual_qpg * hpb;
  if (tid < valid_rows) {
    float inv = (row_sum > 0) ? 1.0f / row_sum : 0.0f;
    constexpr bool write_final = WRITE_FINAL;
    int const q_final = gi * qpg + tid / hpb;
    int const h_final = tid % hpb;

    for (int vc = 0; vc < V_CHUNKS; vc++) {
      int out_taddr_vc = taddr + vc * BK;
      // Issue all 4 column-loads for this V-chunk BEFORE the wait so
      // their TMEM-load latencies overlap (v004 batching: 1 wait/chunk
      // vs 1 wait/load → 8 exposed latencies instead of 32).
      float t[4][16];
#pragma unroll
      for (int j = 0; j < 4; j++) {
        int addr = out_taddr_vc + (tid << 16) + j * 16;
        asm volatile(
            "tcgen05.ld.sync.aligned.32x32b.x16.b32 "
            "{%0,%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15}, [%16];"
            : "=f"(t[j][0]),
              "=f"(t[j][1]),
              "=f"(t[j][2]),
              "=f"(t[j][3]),
              "=f"(t[j][4]),
              "=f"(t[j][5]),
              "=f"(t[j][6]),
              "=f"(t[j][7]),
              "=f"(t[j][8]),
              "=f"(t[j][9]),
              "=f"(t[j][10]),
              "=f"(t[j][11]),
              "=f"(t[j][12]),
              "=f"(t[j][13]),
              "=f"(t[j][14]),
              "=f"(t[j][15])
            : "r"(addr));
      }
      asm volatile("tcgen05.wait::ld.sync.aligned;");
#pragma unroll
      for (int j = 0; j < 4; j++) {
        int base_d = (vc * BK + j * 16) * 128 + tid;
#pragma unroll
        for (int i = 0; i < 16; i++) {
          nv_bfloat16 val = __float2bfloat16(t[j][i] * inv);
          if (write_final) {
            // WRITE_FINAL=true: direct final output store
            int const o_base =
                (bi * Q_LEN + q_final) * NUM_HEADS * D_V + h_final * D_V;
            asm volatile(
                "st.global.cs.b16 [%0], %1;" ::"l"(
                    (nv_bfloat16 *)(Oa + o_base + vc * BK + j * 16 + i)),
                "h"(*(uint16_t *)&val)
                : "memory");
          } else {
            // WRITE_FINAL=false: partial-O layout for reduce
            asm volatile("st.global.cs.b16 [%0], %1;" ::"l"(
                             (nv_bfloat16 *)(Oout + base_d + i * 128)),
                         "h"(*(uint16_t *)&val)
                         : "memory");
          }
        }
      }
    }
    if (!write_final) {
      // Store LSE in log2 domain: log2(sum) + max_in_log2e_scale
      La[block_linear * 128 + tid] = log2f(fmaxf(row_sum, 1e-30f)) + row_max;
    }
  }

  // tcgen05.dealloc from warp 0 (same warp as alloc — CuTe invariant).
  MLA_TP_SYNC_ACTIVE();
  if (wid == 0) {
    asm volatile(
        "tcgen05.dealloc.cta_group::1.sync.aligned.b32 %0, %1;" ::"r"(taddr),
        "r"(D_V));
  }
}

// ============ Reduction Kernel ============
// One-pass online softmax reduce over sk splits.
// RD_DV=2, 256 threads: block_x indexes D_V/2 pairs, block_y = gi, block_z =
// bi.
__device__ __noinline__ void
    mla_mtp_tp8_reduce(nv_bfloat16 const *__restrict__ Oa,
                       float const *__restrict__ La,
                       nv_bfloat16 *__restrict__ O,
                       int sk,
                       int num_groups,
                       int Q_LEN,
                       int qpg,
                       int block_x,
                       int block_y,
                       int block_z) {
  if (threadIdx.x >= RD_TB) {
    return;
  }
  // Dual-dispatch gate: TP=8 reduce handles Q_LEN <= 8 (same as main).
  if (Q_LEN > 8) {
    return;
  }
  int const dv_base = block_x * RD_DV;
  int const gi = block_y;
  int const bi = block_z;
  int const tid = threadIdx.x;

  int const row = tid & 127;
  int const lane = tid >> 7;
  int const d = dv_base + lane;

  int q_in_group = row / NUM_HEADS;
  int h = row % NUM_HEADS;
  int actual_q = gi * qpg + q_in_group;

  if (actual_q >= Q_LEN || q_in_group >= qpg || d >= D_V) {
    return;
  }

  float const *la_ptr = La + (bi * num_groups * sk + gi * sk) * 128 + row;
  nv_bfloat16 const *oa_ptr =
      Oa + (bi * num_groups * sk + gi * sk) * D_V * 128 + d * 128 + row;

  if (sk == 1) {
    int o_base = (bi * Q_LEN + actual_q) * NUM_HEADS * D_V + h * D_V;
    O[o_base + d] = oa_ptr[0];
    return;
  }

  // One-pass online softmax reduce — dynamic over sk splits.
  float maxVal = -1e30f, oldMaxVal = -1e30f;
  float sumVal = 0.0f;
  float acc = 0.0f;

  for (int s = 0; s < sk; s++) {
    float localMax = la_ptr[s * 128];
    float oa_val = __bfloat162float(oa_ptr[(size_t)s * D_V * 128]);

    maxVal = fmaxf(maxVal, localMax);
    float corr0 = exp2f(oldMaxVal - maxVal);
    float corr1 = exp2f(localMax - maxVal);
    oldMaxVal = maxVal;

    sumVal = sumVal * corr0 + corr1;
    acc = acc * corr0 + oa_val * corr1;
  }

  float inv_sum = (sumVal > 0.0f) ? __frcp_rn(sumVal) : 0.0f;
  int o_base = (bi * Q_LEN + actual_q) * NUM_HEADS * D_V + h * D_V;
  O[o_base + d] = __float2bfloat16(acc * inv_sum);
}

} // namespace mla_mtp_tp8
} // namespace kernel
