// Ampere task impls
#include "tasks/ampere/clamped_swiglu.cuh"
#include "tasks/ampere/embedding.cuh"
#include "tasks/ampere/identity.cuh"
#include "tasks/ampere/merge_splitkv.cuh"
#include "tasks/ampere/multitoken_paged_attention_split_kv.cuh"
#include "tasks/ampere/silu_mul.cuh"
#include "tasks/ampere/single_batch_extend.cuh"
#ifdef USE_NVSHMEM
#include "tasks/ampere/allreduce.cuh"
#endif // USE_NVSHMEM
// Hopper task impls
#include "tasks/cute/hopper/gemm_ws.cuh"
#include "tasks/cute/hopper/gemm_ws_cooperative.cuh"
#include "tasks/cute/hopper/gemm_ws_mpk.cuh"
#include "tasks/hopper/linear_hopper.cuh"
#include "tasks/hopper/linear_swapAB_hopper.cuh"
#include "tasks/hopper/multitoken_paged_attention_hopper.cuh"
#include "tasks/hopper/rmsnorm_hopper.cuh"
#include "tasks/hopper/rotary_embedding_hopper.cuh"
#include "tasks/hopper/silu_mul_hopper.cuh"
#if defined(USE_NVSHMEM) && !defined(MIRAGE_GRACE_BLACKWELL)
#include "tasks/hopper/allreduce.cuh"
#endif
// Blackwell task impls
#if defined(USE_NVSHMEM) && defined(MIRAGE_GRACE_BLACKWELL)
#include "tasks/blackwell/allreduce.cuh"
#endif
#include "argmax_sm100.cuh"
#if defined(USE_NVSHMEM) && defined(MIRAGE_GRACE_BLACKWELL)
#include "nvshmem_argmax_sm100.cuh"
#endif
#include "attention_sm100.cuh"
#include "deepseek_mla_rope_sm100.cuh"
#include "dflash_attention_sm100.cuh"
#include "dflash_kv_store_sm100.cuh"
#include "dflash_norm_rope_sm100.cuh"
#include "dsv3_router_gate_gemv_sm100.cuh"
#include "elementwise_add_sm100.cuh"
#include "fp8_gemm_dense_mediumm_sm100.cuh"
#include "fp8_gemm_dense_smallm_sm100.cuh"
#include "fp8_group_gemm_largem_sm100.cuh"
#include "fp8_group_gemm_sm100.cuh"
#include "glm_moe_router_sm100.cuh"
#include "inkling_attention_sm100.cuh"
#include "inkling_moe_router_sm100.cuh"
#include "inkling_sconv_sm100.cuh"
#include "linear_fp8_1d2d_sm100.cuh"
#include "fused_rmsnorm_quantize_fp8_sm100.cuh"
#include "linear_fp8_bmm_dense_sm100.cuh"
#include "linear_fp8_bmm_sm100.cuh"
#include "linear_fp8_sm100.cuh"
#include "linear_fp8_swapAB_sm100.cuh"
#include "linear_sm100_mpk.cuh"
#include "mla_kv_append_sm100.cuh"
#include "mla_kv_cache_gather_sm100.cuh"
#include "mla_kv_cache_gather_split_sm100.cuh"
#include "mla_mtp_decode_tp8_sm100.cuh"
#include "mla_prefill_sm100.cuh"
#include "mla_prefill_tp8_chunked_sm100.cuh"
#include "mla_prefill_tp8_sm100.cuh"
#include "moe_linear_sm100.cuh"
#include "moe_permute_sm100.cuh"
#include "moe_unpermute_sm100.cuh"
#include "mul_sum_add_sm100.cuh"
#include "per_token_group_quantize_fp8.cuh"
#include "prob_scatter_sm100.cuh"
#include "sm100_ptx.cuh"
#include "softmax_gather_sm100.cuh"
#include "tasks/common/sampling.cuh"
#include "tasks/speculative_decoding/eagle3_ops.cuh"
#include "tasks/speculative_decoding/mtp_token_ops.cuh"
#include "tasks/speculative_decoding/prompt_lookup.cuh"
#include "tasks/speculative_decoding/target_verify.cuh"
#include "tasks/speculative_decoding/target_verify_mtp.cuh"
#include "tensor_init.cuh"
#include "topk_sigmoid_sm100.cuh"
#include "topk_softmax_sm100.cuh"
