#!/usr/bin/env bash
# M4-I6 GATE 2 -- the megakernel's SHARED register/stack/smem budget, before vs
# after.
#
# WHY IT IS A GATE AND NOT A CURIOSITY: MPK compiles ONE __global__
# (`persistent_kernel`, __launch_bounds__(256,1)) with EVERY task body inlined,
# so ptxas allocates a SINGLE register budget and a SINGLE per-thread stack frame
# for all of them. M3-I6a found the attention accumulator spilling and taxing
# dense-fp8 and GDN -- stages it does not touch. So a router win that raises
# register pressure can REGRESS every other stage and the win would be a mirage.
# The v013 candidate is exactly the shape of change that does this: it holds a
# per-lane 16-entry u64 sorted key list PLUS a descending copy PLUS the buffered
# top-k values, all live across the k-loop.
#
# THIS GATE ALSO CHECKS SMEM, which the earlier campaigns did not need to. The
# candidate is the first router body to use shared memory at all (32 B static
# active-expert bitmask at 256 experts), and static task smem lands in
# WORKER_RESERVED_STATIC_SHARED_MEMORY_SIZE, the 6 KiB that is SUBTRACTED from
# MAX_DYNAMIC_SHARED_MEMORY_SIZE. If the reserve were already exhausted, the
# `cudaFuncSetAttribute(persistent_kernel, MaxDynamicSharedMemorySize, 205824)`
# in persistent_kernel.cuh:1863 would start failing. Read the smem line, do not
# assume.
#
# Two TUs, both generated by a real MPK build so the template arguments ship:
#   A  arm A of the sweep (mirage-m4i6-base) -- the BEFORE
#   B  arm B of the sweep (mirage-m4i6)      -- the AFTER
#
# Compile-only: no CUDA API call, no launch, no GPU claim. Flags lifted verbatim
# from m4i2/scripts/mk_ptxas_m4i2.sh, which lifted them from the JIT command in
# the run logs.
set -u
export PATH=/usr/local/cuda-12.8/bin:$PATH
M=${M:-$HOME/mpk-qwen35/m4i6}
S=${S:-/var/tmp/m4i6_sweep}
TA=${TA:-$HOME/mpk-qwen35/mirage-m4i6-base}
TB=${TB:-$HOME/mpk-qwen35/mirage-m4i6}
BS=${BS:-1}
OUT=$M/ptxas
mkdir -p "$OUT"

report () {           # $1 = label, $2 = log
  echo "  --- $1 ---"
  grep -E "Compiling entry function '_Z17persistent_kernel|bytes stack frame|bytes spill|Used [0-9]+ registers|bytes smem|bytes cmem" \
    "$2" | sed 's/^/    /'
}

one () {              # $1 = label, $2 = kernel dir, $3 = TREE the arm was built from
  local LBL="$1" KD="$2" TREE="$3" CU="$2/test_rank0.cu"
  echo "=== $LBL  ($CU)  headers from $(basename "$TREE") ==="
  if [ ! -f "$CU" ]; then echo "  MISSING -- skipped"; return; fi
  # THE INCLUDE PATH IS PER-ARM. The router body is a HEADER, so the generated
  # .cu is (near-)identical between arms and the ONLY thing that selects the
  # arm is which tree's include/ nvcc reads. Pointing both arms at one tree
  # would compile the same kernel twice and report "no change" -- the header
  # analogue of two arms sharing a --kernel-dir.
  local INC="-I/usr/include/python3.12 -I$TREE/include \
 -I$TREE/include/mirage/persistent_kernel \
 -I$TREE/deps/cutlass/include -I$TREE/deps/cutlass/tools/util/include \
 -I$TREE/deps/json/include"
  sha256sum "$CU" | sed 's/^/  TU sha256:     /'
  sha256sum "$TREE/include/mirage/persistent_kernel/tasks/blackwell/topk_softmax_sm100.cuh" \
    | sed 's/^/  router sha256: /'
  grep -o "topk_softmax_task_impl<[^>]*>" "$CU" | sort | uniq -c \
    | sort -rn | head -4 | sed 's/^/  TPL: /'
  nvcc "$CU" -O3 -lineinfo $INC \
    -DMAX_WORKER_PER_SCHEDULER=1 -DMIRAGE_USE_CUTLASS_KERNEL=0 \
    -gencode=arch=compute_100a,code=sm_100a \
    -DMPK_ENABLE_TMA -DMIRAGE_GRACE_BLACKWELL \
    -DMPK_TARGET_CC=100 -DMIRAGE_BACKEND_USE_CUDA -DMODE_OFFLINE \
    -DMPK_MAX_NUM_BATCHED_REQUESTS=$BS -DMPK_MAX_NUM_BATCHED_TOKENS=16 \
    -DMPK_MAX_NUM_PAGES=64 -DMPK_PAGE_SIZE=256 -DMPK_MAX_SEQ_LENGTH=353 \
    -shared -std=c++17 -rdc=false -use_fast_math -lcuda -lcudart -lstdc++fs \
    -Xcompiler=-fPIC --expt-relaxed-constexpr -Xptxas -v \
    -o "$OUT/$LBL.so" > "$OUT/${LBL}_bs${BS}.log" 2>&1
  echo "  rc=$?"
  report "$LBL" "$OUT/${LBL}_bs${BS}.log"
  rm -f "$OUT/$LBL.so"
}

echo "########## M4-I6 ptxas -v, bs=$BS  $(date -Is) ##########"
nvcc --version | tail -2
one A "$S/kernel_A_bs${BS}" "$TA"
one B "$S/kernel_B_bs${BS}" "$TB"

echo
echo "=== the two TUs must differ ONLY in the router body ==="
if [ -f "$S/kernel_A_bs${BS}/test_rank0.cu" ] && [ -f "$S/kernel_B_bs${BS}/test_rank0.cu" ]; then
  echo "  generated-TU diff lines: $(diff "$S/kernel_A_bs${BS}/test_rank0.cu" "$S/kernel_B_bs${BS}/test_rank0.cu" | wc -l)"
  echo "  (the router body is a HEADER, so the generated .cu itself should be"
  echo "   identical -- the delta lives in the included topk_softmax_sm100.cuh)"
  diff "$S/kernel_A_bs${BS}/test_rank0.cu" "$S/kernel_B_bs${BS}/test_rank0.cu" | head -20 | sed 's/^/    /'
fi
echo
echo "=== side by side ==="
for L in A B; do
  printf '  %s: %s | %s | %s | %s\n' "$L" \
    "$(grep -oE 'Used [0-9]+ registers' "$OUT/${L}_bs${BS}.log" | head -1)" \
    "$(grep -oE '[0-9]+ bytes stack frame' "$OUT/${L}_bs${BS}.log" | head -1)" \
    "$(grep -oE '[0-9]+ bytes spill stores' "$OUT/${L}_bs${BS}.log" | head -1)" \
    "$(grep -oE '[0-9]+ bytes smem' "$OUT/${L}_bs${BS}.log" | head -1)"
done
echo "MK_PTXAS_M4I6_DONE $(date -Is)"
