#include "argmax.cuh"
#include "embedding.cuh"
// #include "linear.cuh"
#include "linear_cutlass.cuh"
#include "multitoken_paged_attention.cuh"
// #include "norm_linear.cuh"
// #include "paged_attention.cuh"
#include "reduction.cuh"
#include "rmsnorm.cuh"
#include "rotary_embedding.cuh"
#include "silu_mul.cuh"
// #include "silu_mul_linear.cuh"
#include "single_batch_decoding.cuh"
#include "single_batch_extend.cuh"
#include "speculative_decoding/prompt_lookup.cuh"
#include "speculative_decoding/target_verify.cuh"
// Hopper kernels
#include "hopper/linear_hopper.cuh"
#include "hopper/linear_swapAB_hopper.cuh"
#include "hopper/multitoken_paged_attention_hopper.cuh"
#include "hopper/rmsnorm_hopper.cuh"
