#include "argmax.cuh"
#include "embedding.cuh"
// #include "linear.cuh"
#include "linear_cutlass.cuh"
#include "multitoken_paged_attention.cuh"
// #include "norm_linear.cuh"
// #include "paged_attention.cuh"
#include "reduction.cuh"
#include "rmsnorm.cuh"
#include "rotary_embedding.cuh"
#include "silu_mul.cuh"
// #include "silu_mul_linear.cuh"
#include "single_batch_decoding.cuh"
#include "single_batch_extend.cuh"
#include "speculative_decoding/prompt_lookup.cuh"
#include "speculative_decoding/target_verify.cuh"
// Hopper kernels
#include "cute/hopper/gemm_ws.cuh"
#include "cute/hopper/gemm_ws_cooperative.cuh"
#include "cute/hopper/gemm_ws_mpk.cuh"
#include "hopper/embedding_hopper.cuh"
#include "hopper/linear_hopper.cuh"
#include "hopper/linear_swapAB_hopper.cuh"
#include "hopper/multitoken_paged_attention_hopper.cuh"
#include "hopper/rmsnorm_hopper.cuh"
#include "hopper/silu_mul_hopper.cuh"
// SM100 kernels
#include "blackwell/linear_sm100_mpk.cuh"
#include "blackwell/attention_sm100.cuh"
#include "blackwell/argmax_sm100.cuh"

