#!/usr/bin/env bash
# M4-I2: the HEAD control. Two things the A/B cannot establish about itself:
#
#  1. ptxas "vs HEAD" literally -- Gate 2 wants the register budget of the
#     PRE-M4-I2 tree, so that tree has to generate its own megakernel TU.
#  2. that arm A (MPK_FP8_DENSE_BASELINE=1) really is a faithful stand-in for
#     HEAD. Arm A's TU is generated by the new tree; if the knob is honest its
#     wall time matches HEAD's. If it did not, every speedup in the A/B would be
#     measured against a strawman.
#
# Runs in the pre-M4-I2 worktree (/var/tmp/m4i2_head, its own freshly built
# extension -- STALE-EXTENSION TRAP) with the SAME geometry, seeds, kernel-dir
# discipline and drain gate as sweep_fp8.sh.
set -uo pipefail
export PATH=/usr/local/cuda-12.8/bin:$PATH
export HF_HOME=$HOME/mpk-qwen35/hf
export PYTHONUNBUFFERED=1
GPU="${CUDA_VISIBLE_DEVICES:?the guard must pin CUDA_VISIBLE_DEVICES}"

H=${H:-/var/tmp/m4i2_head}
ACC=$H/demo/qwen3_5/accept
export MPK_ACCEPT_DIR=$ACC
export PYTHONPATH=$H/python
PY=$HOME/mpk-qwen35/venv-rm/bin/python
M=${M:-/var/tmp/m4i2_sweep}
KD=${KD:-/var/tmp/m4i2_headkd}
SEED_BASE=20260729
BS=${BS:-1}
REPS="${REPS:-0 1 2}"
MSL=353
NEWTOK=96
OD=$M/noprof_HEAD
mkdir -p "$OD" "$M/logs" "$M/audit"

echo "########## M4-I2 HEAD control  gpu=$GPU  $(date -Is) ##########"
echo "worktree: $H  HEAD=$(git -C "$H" rev-parse --short HEAD) $(git -C "$H" log -1 --format=%s)"
"$PY" -c "import sys;sys.path.insert(0,'$H/python');import mirage,os;print('mirage from',os.path.realpath(mirage.__file__))"
echo "task279 kernel (must be the PRE-port file):"
sha256sum "$H/include/mirage/persistent_kernel/tasks/blackwell/linear_fp8_blockscale_sm100.cuh"
grep -c "task_impl_fast" "$H/include/mirage/persistent_kernel/tasks/blackwell/linear_fp8_blockscale_sm100.cuh" \
  | sed 's/^/  occurrences of task_impl_fast (must be 0): /'

smi () { nvidia-smi --query-gpu=index,memory.used,utilization.gpu --format=csv,noheader,nounits; }
used_on_pinned () { smi | awk -F',' -v g="$GPU" '{gsub(/ /,"",$1)} $1+0==g+0 {gsub(/ /,"",$2); print $2+0}'; }
drain () {
  local i used
  for i in $(seq 1 90); do
    used=$(used_on_pinned); [ "${used:-9999}" -lt 500 ] && return 0; sleep 5
  done
  echo "    ABORT: device $GPU held ${used}MiB after 450s"; exit 97
}

for REP in $REPS; do
  TAG=HEAD_bs${BS}_rep${REP}
  [ -f "$OD/meta_bs${BS}_rep${REP}_HEAD.json" ] && { echo "  [$TAG] cached"; continue; }
  SEED=$((SEED_BASE + BS*1000 + REP))
  RK=""; [ -f "$KD/task_graph_rank0.json" ] && RK="--reuse-kernel"
  drain
  smi > "$M/audit/gpu_before_${TAG}.txt"
  timeout 5400 "$PY" -u "$ACC/opt/profile_wave.py" \
      --batch-size "$BS" --max-seq-length "$MSL" --max-new-tokens "$NEWTOK" --mbt 16 \
      --page-size 256 --synthetic-prompt-len 256 --synthetic-seed "$SEED" \
      --out-dir "$OD" --kernel-dir "$KD" --rep "$REP" --no-profiler $RK \
      > "$M/logs/${TAG}.log" 2>&1
  echo "  [$TAG] rc=$? $(grep -h 'wall=' "$M/logs/${TAG}.log" | tail -1)"
  f=$OD/meta_bs${BS}_rep${REP}.json
  [ -f "$f" ] && mv "$f" "$OD/meta_bs${BS}_rep${REP}_HEAD.json"
  g=$OD/tokens_bs${BS}_rep${REP}.json
  [ -f "$g" ] && mv "$g" "$OD/tokens_bs${BS}_rep${REP}_HEAD.json"
done

echo "--- generated TU for Gate 2 ---"
ls -la "$KD/test_rank0.cu" 2>/dev/null
grep -o "linear_fp8_blockscale_task_impl<[^>]*>" "$KD/test_rank0.cu" 2>/dev/null | sort -u | sed 's/^/  TPL: /'
echo "HEAD_CONTROL_DONE $(date -Is)"
