#!/usr/bin/env bash
# M4-I2 GATE 2 -- the megakernel's SHARED register budget, before vs after.
#
# WHY IT IS A GATE AND NOT A CURIOSITY: MPK compiles ONE __global__
# (`persistent_kernel`, __launch_bounds__(256,1)) with EVERY task body inlined,
# so ptxas allocates a SINGLE register budget and a SINGLE per-thread stack frame
# for all of them. M3-I6a found the attention accumulator spilling and taxing
# dense-fp8 and GDN, stages it does not touch. So a dense-fp8 win that raises
# register pressure can REGRESS every other stage, and the win would be a
# mirage. The ferret fast path adds live state (paired-tile partials,
# double-buffered a_frag/b_frag), which is exactly the shape of change that does
# this.
#
# Three TUs, all generated by a real MPK build so the template arguments are the
# ones that ship:
#   head  /var/tmp/m4i2_head   pre-M4-I2 tree            -- the BEFORE
#   A     arm A of the sweep   MPK_FP8_DENSE_BASELINE=1  -- control: must equal
#                                                          head, which is what
#                                                          licenses using arm A
#                                                          as the e2e baseline
#   B     arm B of the sweep   default                   -- the AFTER
#
# Compile-only: no CUDA API call, no launch, no GPU claim. Flags are lifted
# verbatim from m4i5/scripts/mk_ptxas_m4i5.sh, which lifted them from the JIT
# command in the run logs.
set -u
export PATH=/usr/local/cuda-12.8/bin:$PATH
M=${M:-$HOME/mpk-qwen35/m4i2}
S=${S:-/var/tmp/m4i2_sweep}
HEADKD=${HEADKD:-/var/tmp/m4i2_headkd}
T=${T:-$HOME/mpk-qwen35/mirage-m4i2}
BS=${BS:-1}
OUT=$M/ptxas
mkdir -p "$OUT"

INC="-I/usr/include/python3.12 -I$T/include -I$T/include/mirage/persistent_kernel \
 -I$T/deps/cutlass/include -I$T/deps/cutlass/tools/util/include \
 -I$T/deps/json/include"

report () {           # $1 = label, $2 = log
  echo "  --- $1 ---"
  grep -E "Compiling entry function '_Z17persistent_kernel|bytes stack frame|bytes spill|Used [0-9]+ registers|bytes smem" \
    "$2" | sed 's/^/    /'
}

one () {              # $1 = label, $2 = kernel dir
  local LBL="$1" KD="$2" CU="$2/test_rank0.cu"
  echo "=== $LBL  ($CU) ==="
  if [ ! -f "$CU" ]; then echo "  MISSING -- skipped"; return; fi
  sha256sum "$CU" | sed 's/^/  TU sha256: /'
  # the dense-fp8 task's actual template args, so the slice is visible in the TU
  grep -o "linear_fp8_blockscale_task_impl<[^>]*>" "$CU" | sort | uniq -c \
    | sort -rn | head -8 | sed 's/^/  TPL: /'
  nvcc "$CU" -O3 -lineinfo $INC \
    -DMAX_WORKER_PER_SCHEDULER=1 -DMIRAGE_USE_CUTLASS_KERNEL=0 \
    -gencode=arch=compute_100a,code=sm_100a \
    -DMPK_ENABLE_TMA -DMIRAGE_GRACE_BLACKWELL \
    -DMPK_TARGET_CC=100 -DMIRAGE_BACKEND_USE_CUDA -DMODE_OFFLINE \
    -DMPK_MAX_NUM_BATCHED_REQUESTS=$BS -DMPK_MAX_NUM_BATCHED_TOKENS=16 \
    -DMPK_MAX_NUM_PAGES=64 -DMPK_PAGE_SIZE=256 -DMPK_MAX_SEQ_LENGTH=353 \
    -shared -std=c++17 -rdc=false -use_fast_math -lcuda -lcudart -lstdc++fs \
    -Xcompiler=-fPIC --expt-relaxed-constexpr -Xptxas -v \
    -o "$OUT/$LBL.so" > "$OUT/$LBL.log" 2>&1
  echo "  rc=$?"
  report "$LBL" "$OUT/$LBL.log"
  rm -f "$OUT/$LBL.so"
}

echo "########## M4-I2 ptxas -v, bs=$BS  $(date -Is) ##########"
nvcc --version | tail -2
one head "$HEADKD"
one armA "$S/kernel_A_bs${BS}"
one armB "$S/kernel_B_bs${BS}"

echo
echo "=== head vs armA: the control (the baseline knob must reproduce HEAD) ==="
if [ -f "$OUT/head.log" ] && [ -f "$OUT/armA.log" ]; then
  H=$(grep -oE "Used [0-9]+ registers" "$OUT/head.log" | head -1)
  A=$(grep -oE "Used [0-9]+ registers" "$OUT/armA.log" | head -1)
  echo "  head: $H     armA: $A"
  if [ -f "$HEADKD/test_rank0.cu" ] && [ -f "$S/kernel_A_bs${BS}/test_rank0.cu" ]; then
    if diff -q "$HEADKD/test_rank0.cu" "$S/kernel_A_bs${BS}/test_rank0.cu" >/dev/null; then
      echo "  TU diff: IDENTICAL -- arm A's generated code IS the pre-M4-I2 code"
    else
      echo "  TU diff: differs; lines:"
      diff "$HEADKD/test_rank0.cu" "$S/kernel_A_bs${BS}/test_rank0.cu" | head -30 | sed 's/^/    /'
    fi
  fi
fi
echo "MK_PTXAS_M4I2_DONE $(date -Is)"
