name: "Build Test"

on:
  pull_request:
  push:
    branches:
      - mpk
  workflow_dispatch:

concurrency:
  group: build-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 600

    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive

      - name: Free space on runner
        run: .github/workflows/helpers/free_space_on_runner.sh

      - name: Install CUDA
        uses: Jimver/cuda-toolkit@3d45d157f327c09c04b50ee6ccdea2d9d017ec76 # v0.2.35
        id: cuda-toolkit
        with:
          cuda: "12.1.1"
          use-github-cache: "false"

      - name: Install Dependencies
        run: .github/workflows/helpers/install_dependencies.sh

      - name: Build Mirage from Source
        env:
          CUDA_TOOLKIT_PATH: ${{ steps.cuda-toolkit.outputs.CUDA_PATH }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: .github/workflows/helpers/build_mirage_from_source.sh

      - name: Test Mirage Import
        run: python3 -c "import mirage; print('Mirage import successful!')"
