name: "GPU Tests"
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: gpu-ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  performance-tests:
    name: Performance test
    runs-on: "runs-on=${{ github.run_id }}/runner=gpu-nvidia"
    defaults:
      run:
        shell: bash -l {0}
    env:
      CUDA_PATH: /usr/local/cuda
      CUDACXX: /usr/local/cuda/bin/nvcc
      CONDA: "3"
    steps:
      - name: Set path
        run: echo "/opt/amazon/openmpi/bin:/opt/amazon/efa/bin:/opt/conda/bin:/usr/local/cuda/bin:/usr/local/cuda/include" >> $GITHUB_PATH
      
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Install conda and Mirage dependencies
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: mirage
          environment-file: conda/mirage.yml
          auto-activate-base: false
          auto-update-conda: false
          
      - name: Install Dependencies
        run: .github/workflows/helpers/install_dependencies.sh

      - name: Build Mirage from Source
        run: .github/workflows/helpers/build_mirage_from_source.sh

      - name: Run performance test
        run: |
          tests/ci-tests/run_python_tests.sh before-installation
          tests/ci-tests/run_python_tests.sh after-installation
        
      # Clear cache to prevent affecting subsequent tests
      - name: Clear cache
        if: always()
        run: sudo rm -rf ~/.cache 